### PR TITLE
Capture weak ref to this in AnimatedVisualPlayer::DestroyAnimations lambda

### PR DESCRIPTION
**Pull request by aborziak-ms**
We should capture `this` as a weak reference, because `this` may be destroyed before `RequestCommitAsync` completes. If it is destroyed - we do not need to do anything, just return. This bug causes crashes on app exit sometimes.

### CODE REVIEW

**Review by kmahone — APPROVED** [review]

**Comment by aborziak-ms** [comment]
@kmahone it seems that build fails are not related to the changes in the PR?

**Comment by kmahone** [comment]
> @kmahone it seems that build fails are not related to the changes in the PR?

@aborziak-ms let me try re-run the failed Jobs.

**Comment by kmahone** [comment]
> > @kmahone it seems that build fails are not related to the changes in the PR?
> 
> @aborziak-ms let me try re-run the failed Jobs.

Passed on retry.

**Comment by yaichenbaum** [comment]
@kmahone is it posible this solved #7364?

**Comment by kmahone** [comment]
> @kmahone is it possible this also fixes #7364?

It is likely unrelated.

**Pull request merged**
