### PR TITLE
ContentDialog - supports Min\Max sizes

### PR DESCRIPTION
**Pull request by alexdi220**
## Description
The minimal fix of the issue.

## Motivation and Context
The ContentDialog can't manage Min\Max sizes out of box. This pretty little but annoying bug. Related issue https://github.com/microsoft/microsoft-ui-xaml/issues/424

### CODE REVIEW

**Comment by StephenLPeters** [comment]
@alexdi220 Can you accept the the CLA agreement before we run the pipeline to verify your change? :)

**Comment by alexdi220** [comment]
@StephenLPeters  done

**Comment by StephenLPeters** [comment]
build aged out :/

**Review by karenbtlai — APPROVED** [review]

**Comment by StephenLPeters** [comment]
@karenbtlai these VisualVerification updates don't make sense to me.  Why does the RS2 version of the verification have a RenderSize=320,184 but the RS3 version has RenderSize=0,0?

**Pull request merged**
