### PR TITLE
IsSelectionRequried -> IsSelectionRequired

### PR DESCRIPTION
**Pull request by tony-xia**

### CODE REVIEW

**Review by StephenLPeters — APPROVED** [review]

**Comment by StephenLPeters** [comment]
It looks like the implementation of this function was copied from the CanSelectMultiple, which is wrong: 
```
bool TreeViewListAutomationPeer::CanSelectMultiple()
{	{
    return IsMultiselect()? true: __super::CanSelectMultiple();	    return IsMultiselect()? true: __super::CanSelectMultiple();
}	}


bool TreeViewListAutomationPeer::IsSelectionRequried()	bool TreeViewListAutomationPeer::IsSelectionRequired()
{	{
    return IsMultiselect()? false : __super::CanSelectMultiple();	    return IsMultiselect()? false : __super::CanSelectMultiple();
}	}
```

I think instead this should always return false. When the TreeViewSelectionMode is none, selection is not required, when it is single you can deselect via ctrl click and in multi select you can unselect with a normal click.  @tony-xia could you make this change as well?

Thanks for finding this, it was definitely causing narrator users some pain, this function being misnamed means they weren't being informed of the selection behavior. @ranjeshj who made the orininal change to confirm.  @Felix-Dev who has been exploring this space, do you agree with my assessment that selection is never required for our treeview?

**Review by StephenLPeters — CHANGES_REQUESTED** [review]
.

**Comment by Felix-Dev** [comment]
> do you agree with my assessment that selection is never required for our treeview? 

@StephenLPeters Yes, this sounds correct to me.

**Comment by tony-xia** [comment]
@StephenLPeters  I updated the PR according to your feedback. Please review it again. thanks

**Review by StephenLPeters — APPROVED** [review]

**Comment by StephenLPeters** [comment]
@tony-xia if you could merge master into your working branch, that will pick up the fix for the pipeline error that is blocking your change from being submitted, then we can merge this fix in!

**Comment by ranjeshj** [comment]
Returning false sounds right. There are some controls where we want to always have an item selected, but treeview allows deselecting so I think this makes sense. Thanks for the fix @tony-xia.

**Comment by tony-xia** [comment]
@StephenLPeters i merged master into my working branch. thanks

**Pull request merged**
