### PR TITLE
Fix generateproject script

### LINKED ISSUE #2800: GenerateNewControlProject.ps1 hits error: "Could not load file or assembly 'EnvDTE, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
Running tools\GenerateNewControlProject.ps1 hits an error:

```
Add-Type : Could not load file or assembly 'EnvDTE, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
At D:\microsoft-ui-xaml\tools\GenerateNewControlProject.ps1:176 char:1
+ Add-Type -ReferencedAssemblies $assemblies -TypeDefinition $source -L ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-Type], FileNotFoundException
    + FullyQualifiedErrorId : System.IO.FileNotFoundException,Microsoft.PowerShell.Commands.AddTypeCommand

Unable to find type [SolutionHelper.SolutionRegister515533087].
At line:1 char:1
+ [SolutionHelper.SolutionRegister515533087]::Main()
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (SolutionHelper.SolutionRegister515533087:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound

```

Both myself and @chenss3 hit this when trying to run the script. I tried to workaround the issue by fully specifying the path to EnvDTE.dll and EnvDTE80.dll, but that did not resolve the problem.

This script got updated by #2145. @chingucoding would you be able to take a look?

### PR DESCRIPTION
**Pull request by chingucoding**
## Description

Now we load the assemblies "manually" instead of using Add-Type.
This also cleans up an usused variable in the c# code.
## Motivation and Context

Fixes #2800
## How Has This Been Tested?

Tested manually
## Screenshots (if appropriate):

@kmahone @chenss3 Hopefully this unblocks you :)

### CODE REVIEW

**Comment by kmahone** [comment]
Thanks for taking a look. 

I tried out this updated script, but hit the same issue. Very strange, I can't tell what is causing the assembly to fail to load.

**Comment by chingucoding** [comment]
Can you try placing the following line in there with the updated paths (should just be switching the Community with your version)?

```
[void]([System.Reflection.Assembly]::LoadFrom("C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\PublicAssemblies\envdte.dll"))
[void]([System.Reflection.Assembly]::LoadFrom("C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\PublicAssemblies\envdte80.dll"))

```

**Comment by kmahone** [comment]
Let me give it a shot.

**Comment by kmahone** [comment]
Nice. That helped the script make progress. I hit a later error:

```
Started script
...
Adding test UI
Exception calling "Main" with "0" argument(s): "This operation is not supported for a relative URI."
```

I was able to fix that by fixing the forward slashes on the next line to escaped backslashes:

`newControlFolder.AddFromFile("$($cleanMuxControlsDir)dev\\$($controlName)\\TestUI\\$($controlName)_TestUI.shproj");`

Now we just need a way to ensure that the dlls get loaded without having to hard-code the path in the script. You can probably use vswhere to do that. Take a look at DevCmd.cmd for an idea of how to use it.

**Comment by chingucoding** [comment]
Great to hear that it helped. After changing that line, are there any other errors you encountered? Or do I just need to fix that line (beside loading the dll of course)? Unfortunately, the issue doesn't happen on my machine.

**Comment by kmahone** [comment]
Once I fixed that line, the script worked correctly.

**Comment by chingucoding** [comment]
Awesome I'll update the script accordingly.

**Comment by chingucoding** [comment]
I've update the script now, it loads the dll's now by getting the VS install location.

**Comment by kmahone** [comment]
Everything seems to be working now. Thanks for making the changes.

**Pull request merged**
