### PR TITLE
[AutoSuggestBox] Fix bug where find icon would be placed incorrectly in control

### LINKED ISSUE #5537: WinUI 2.6.1 AutoSuggestBox Search Icon Position Offset
**Describe the bug**
The search icon on the AutoSuggestBox seems offset too far to the left or not right-justified.

**Steps to reproduce the bug**
Seems to be the default with no steps needed to reproduce.

**Expected behavior**
The icon ought to be right justified like it was on WinUI 2.5. No overlapping with search text or placeholder text.

**Screenshots**
image

image

image

**Version Info**
2.6.1

NuGet package version: 
[Microsoft.UI.Xaml 2.6.1]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (21H2)              | Yes |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

### PR DESCRIPTION
**Pull request by chingucoding**
## Description

The issue was that the placeholder present was placed in all 4 columns even though it should have only be placed in two columns
## Motivation and Context

Closes #5537
## How Has This Been Tested?

Tested manually.

### CODE REVIEW

**Comment by StephenLPeters** [comment]
@chingucoding FYI on the visual verification files

**Comment by chingucoding** [comment]
Updated now, thanks @StephenLPeters

**Comment by chingucoding** [comment]
Looks like we have verification test failures, however the newly published verification files don't contain any changes. @StephenLPeters @kaiguo Do you have any idea what we could do here (maybe just rerun?)?

**Comment by chingucoding** [comment]
I've updated the verification files, however the script does not work as expected; it suggested just flat out deleting two files instead of updating the existing files. Is this just something that happens on my machine or is this worth investigating further?

**Pull request merged**
