### PR TITLE
Change IconSource.CreateIconElement to a "dynamic" factory.

### PR DESCRIPTION
**Pull request by StephenLPeters**
Change IconSource's CreateIconElement to make the IconSource behave as a "dynamic" factory. IconSource now records the icons created by it and pushes properties changed on the icon source to those icon elements. To minimize Compat issues, I've reverted all of the usages of the createIconElement except animated icon's back to the shared helper.

### CODE REVIEW

**Comment by ranjeshj** [comment]
@jevansaks @MikeHillberg This is trying to solve the issue where if the IconSource's properties change after the Icon has been created from it, the created icons react to it. Is there a simpler way to listen to any property change on a dependency object ? That would save us from having to maintain this. Also any custom IconSources are not going to get this behavior.

**Comment by ranjeshj** [comment]
The alternative/workaround to this would be to ask people to bind the IconSource property, change the IconSource property itself instead of binding to say the glyph of a font icon under the icon source. We can respond to the IconSource property changed and update the Icon we create.

**Comment by StephenLPeters** [comment]
> @jevansaks @MikeHillberg This is trying to solve the issue where if the IconSource's properties change after the Icon has been created from it, the created icons react to it. Is there a simpler way to listen to any property change on a dependency object ? That would save us from having to maintain this. Also any custom IconSources are not going to get this behavior.

Custom IconSources aren't actually a thing, because IconSource doesn't have a public constructor so you can't derive from it outside of our project.

**Comment by StephenLPeters** [comment]
> The alternative/workaround to this would be to ask people to bind the IconSource property, change the IconSource property itself instead of binding to say the glyph of a font icon under the icon source. We can respond to the IconSource property changed and update the Icon we create.

This doesn't help us template bind a font icon source's font size to the control's font size property, for example.

**Review by ranjeshj — APPROVED** [review]
:shipit:

**Pull request merged**
