### PR TITLE
NavView: Navigation does not work when using Narrator in Scan Mode

### LINKED ISSUE #5998: [NavigationView] Navigation does not work when using Narrator in Scan Mode
### Describe the bug

When using Narrator in scan mode, the NavigationView does not trigger the click event and does not allow for navigation. Clicking enter will announce the title of the NavigationViewItem, and the selection indicator will move to the item but the page does not load.

PowerToys got flagged on this issue: https://github.com/microsoft/PowerToys/issues/7027

### Steps to reproduce the bug

1. Open XAML Controls Gallery
2. Turn on Narrator and press Caps Lock + Space to turn on Scan Mode
3. Navigate to a NavigationViewItem and press enter
4. Page does not load

### Expected behavior

That the selected event would be triggered and the page shows

### Screenshots

In this GIF, I first navigate with scan mode on and turned off. As you can see, navigation with scan mode on does not work.

NavView problem

### NuGet package version

_No response_

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

May 2021 Update (19043)

### Additional context

Both in XAML Islands (PowerToys) as UWP (XAML Controls Gallery) this does not work

### PR DESCRIPTION
**Pull request by kmahone**
NavViewItem AutomationPeer was intended to support Invoke Pattern, but didn't return correctly for GetPatternCore.
Not supporting Invoke causes problems when interacting with NavView via UIA, particularly when using Scan Mode in Narrator.

Closes #5998

### CODE REVIEW

**Comment by kmahone** [comment]
Looks like NavViewItem AP not supporting Invoke pattern was an intentional change:
**NavigationViewItem tab control type supports invoke pattern with PaneDisplayMode="Top" #2702**

**Review by ojhad — APPROVED** [review]

**Comment by kmahone** [comment]
Since we don't want to add Invoke back to NavViewItem AP (because of #2702), we instead double up UIA SelectionItem.Select() to also do an invoke. This makes SelectionItem.Select() equivalent to clicking on the item which is what desired in most cases.

**Comment by kmahone** [comment]
@ojhad can you take a look at the latest iteration?

**Review by ojhad — APPROVED** [review]

**Pull request merged**
