### PR TITLE
Removed Win 10x line item

### PR DESCRIPTION
**Pull request by shaggygi**
## Description
Removing line item since it was confirmed Win 10x is not going to be released.

See link for more details.
https://blogs.windows.com/windowsexperience/2021/05/18/how-to-get-the-windows-10-may-2021-update/

## Motivation and Context
No longer a provided feature.

## How Has This Been Tested?
N/A

## Screenshots (if appropriate):
N/A

### CODE REVIEW

**Comment by StephenLPeters** [comment]
@anawishnoff want to sign off?

**Comment by anawishnoff** [comment]
Hey @shaggygi, I'm planning on doing a bigger update to this doc within the next month or so - holding off on this for now, but I'll merge when we begin those bigger changes. Thanks!

**Comment by StephenLPeters** [comment]
I'm going to close the PR, we can reopen when the doc update comes.

**Pull request closed without merging**
