### PR TITLE
Add filter for Repeater folder

### PR DESCRIPTION
**Pull request by chingucoding**
## Description

Add vcx filter to make Repeater source code be more easy to browse in solution view.

## Motivation and Context

Addresses #1303 
## Screenshots (if appropriate):

image

### CODE REVIEW

**Comment by ranjeshj** [comment]
@chingucoding Thanks for updating this. I think the following hierarchy would better align the way things are organized.
CollectionServices	
	Common
		CustomProperty.cpp
		CustomProperty.h
		IndexPath.cpp
		IndexPath.h
		IndexRange.cpp
		IndexRange.h
		RepeaterTestHooks.cpp
		RepeaterTestHooks.h
		RepeaterTestHooks.idl
		RepeaterTestHooksFactory.cpp
		RepeaterTestHooksFactory.h
		RepeaterTrace.h
	ItemsRepeater
		ItemsRepeater.common.cpp
		ItemsRepeater.common.h
		ItemsRepeater.cpp
		ItemsRepeater.h
		ItemsRepeater.idl
		RepeaterPrivate.idl
		ItemsRepeaterElementClearingEventArgs.cpp
		ItemsRepeaterElementClearingEventArgs.h
		ItemsRepeaterElementIndexChangedEventArgs.cpp
		ItemsRepeaterElementIndexChangedEventArgs.h
		ItemsRepeaterElementPreparedEventArgs.cpp
		ItemsRepeaterElementPreparedEventArgs.h
		ItemsRepeaterScrollHost.cpp
		ItemsRepeaterScrollHost.h
		RepeaterLayoutContext.cpp
		RepeaterLayoutContext.h
		UniqueIdElementPool.cpp
		UniqueIdElementPool.h
		ViewManager.cpp
		ViewManager.h
		ViewportManager.h
		ViewportManagerDownlevel.cpp
		ViewportManagerDownlevel.h
		ViewportManagerWithPlatformFeatures.cpp
		ViewportManagerWithPlatformFeatures.h
		VirtualizationInfo.cpp
		VirtualizationInfo.h
		VirtualizingLayout.cpp
		VirtualizingLayout.h
		VirtualizingLayoutContext.cpp
		VirtualizingLayoutContext.h
		VirtualLayoutContextAdapter.cpp
		VirtualLayoutContextAdapter.h
		ChildrenInTabFocusOrderIterable.cpp
		ChildrenInTabFocusOrderIterable.h
		Layout.cpp
		Layout.h
		LayoutContext.cpp
		LayoutContext.h
		LayoutContextAdapter.cpp
		LayoutContextAdapter.h
		NonVirtualizingLayout.cpp
		NonVirtualizingLayout.h
		NonvirtualizingLayoutContext.cpp
		NonvirtualizingLayoutContext.h
	   Phasing
		BuildTreeScheduler.cpp
		BuildTreeScheduler.h
		Phaser.cpp
		Phaser.h
		QPCTimer.cpp
		QPCTimer.h
	   Animations
		AnimationManager.cpp
		AnimationManager.h
		ElementAnimator.cpp
		ElementAnimator.h
	   ItemsSource
		ItemsSourceView.cpp
		ItemsSourceView.h
		ItemsSourceViewFactory.cpp
		ItemsSourceViewFactory.h
		InspectingDataSource.cpp
		InspectingDataSource.h
	   ItemTemplate
		ElementFactory.cpp
		ElementFactory.h
		ElementFactoryGetArgs.cpp
		ElementFactoryGetArgs.h
		ElementFactoryGetArgsDownlevel.cpp
		ElementFactoryGetArgsDownlevel.h
		ElementFactoryRecycleArgs.cpp
		ElementFactoryRecycleArgs.h
		ElementFactoryRecycleArgsDownlevel.cpp
		ElementFactoryRecycleArgsDownlevel.h
		ItemTemplateWrapper.cpp
		ItemTemplateWrapper.h
		RecyclePool.cpp
		RecyclePool.h
		RecyclePoolFactory.cpp
		RecyclePoolFactory.h
		RecyclingElementFactory.cpp
		RecyclingElementFactory.h
		SelectTemplateEventArgs.cpp
		SelectTemplateEventArgs.h
	Layouts
		FlowLayout
			ElementManager.cpp
			ElementManager.h
			FlowLayout.cpp
			FlowLayout.h
			FlowLayoutAlgorithm.cpp
			FlowLayoutAlgorithm.h
			FlowLayoutState.cpp
			FlowLayoutState.h
			IFlowLayoutAlgorithmDelegates.h
			OrientationBasedMeasures.cpp
			OrientationBasedMeasures.h
		StackLayout
			StackLayout.cpp
			StackLayout.h
			StackLayoutState.cpp
			StackLayoutState.h
		UniformGridLayout
			UniformGridLayout.cpp
			UniformGridLayout.h
			UniformGridLayoutState.cpp
			UniformGridLayoutState.h
	Selection
		SelectedItems.h
		SelectionModel.cpp
		SelectionModel.h
		SelectionModelChildrenRequestedEventArgs.cpp
		SelectionModelChildrenRequestedEventArgs.h
		SelectionModelSelectionChangedEventArgs.cpp
		SelectionModelSelectionChangedEventArgs.h
		SelectionNode.cpp
		SelectionNode.h
		SelectionTreeHelper.cpp
		SelectionTreeHelper.h
	Automation	
		RepeaterAutomationPeer.cpp
		RepeaterAutomationPeer.h
		RepeaterAutomationPeer.idl

**Comment by chingucoding** [comment]
Thanks @ranjeshj for the great diagram! I have updated the filters accordingly,

**Comment by StephenLPeters** [comment]
@ranjeshj does this look good to go?

**Comment by ranjeshj** [comment]
all good !

**Pull request merged**
