### PR TITLE
Fix AutoSuggestBox not respecting common TextBox properties

### LINKED ISSUE #2249: AutoSuggestBox should respect typical TextBox properties
**Describe the bug**
Currently, the `AutoSugestBox` control does not respect (at least) the following common `TextBox` properties even though it exposes them:
* Foreground
* Background
* BorderBrush
* BorderThickness

If someone wants to customize them they currently have to use lightweight styling (theme resources). We should also consume these properties for the AutoSuggestBox control to a) reduce confusion (why isn't the specified value respected) and b) provide a familiar experience with other text controls like TextBox.

**Expected behavior**
The above properties will be respected.

**Screenshots**
The following XAML results in the picture below:
```xml
<AutoSuggestBox MinWidth="200" 
                Foreground="Blue" 
                BorderBrush="Orange"
                BorderThickness="2"
                Background="#FF404040"
                Header="AutoSuggestBox"/>
<TextBox MinWidth="200" 
         Margin="0,10,0,0"
         Foreground="Blue"
         BorderThickness="2"
         BorderBrush="Orange"
         Background="#FF404040"
         Header="TextBox"/>
```

image

**Version Info**

NuGet package version: 
WinUI 2.3 (and newest 2.4 preview)

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| November 2019 Update (18363)  | Yes   |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**
I would like to fix this.

### PR DESCRIPTION
**Pull request by Felix-Dev**
## Description
This PR makes the `AutoSuggestBox` control consume the following properties now:
* Foreground
* Background
* BorderBrush
* BorderThickness

## Motivation and Context
Fixes #2249.

## How Has This Been Tested?
Tested visually.

## Screenshots (if appropriate):
The following XAML gives the look below:
```xml
<AutoSuggestBox Header="AutoSuggestBox" MinWidth="200"
                Foreground="Blue"
                Background="#FF404040"
                BorderBrush="Orange"
                BorderThickness="2"/>
```
image

### CODE REVIEW

**Comment by StephenLPeters** [comment]
@Felix-Dev as expected the visual tree verification tests failed. Can you please update the masters?

**Comment by Felix-Dev** [comment]
@StephenLPeters should I wait until commit #2198 is merged into master, we ran the tests here again and I can use the new visual tree masters now containing #2198 changes too?

**Comment by kmahone** [comment]
There was a test failure in the previous run of the build. However the builds get cleaned up after a while, so it is no longer available.

I've kicked off another run of the build. Once that is available we will be able to investigate. Likely an xml master file needs to be updated.

**Comment by kmahone** [comment]
I've merged the latest from master and updated the xml masters. I've kicked off another run of the build which should pass the tests now.

**Comment by kmahone** [comment]
Missed a set of masters in the previous push. I think it should be good now.

**Comment by kmahone** [comment]
Hmmm. Another xml dump verification failure. I'll take a look.

**Pull request merged**
