### PR TITLE
NavigationView: Fix IsPaneOpen=false ignored on launch when pane is launched in Left expanded state

### LINKED ISSUE #2391: Show NavigationPane on collapsed by default on PaneDisplayMode Left
**Describe the bug**
Unable to show NavigationPane collapsed by default for PaneDisplayMode Left

**Steps to reproduce the bug**
1. Create a new UWP App
2. Add a NavigationView Control to the MainPage
3. Set PaneDisplayMode to Left and IsPaneOpen to false

I've attached a repro project : [App207.zip](https://github.com/microsoft/microsoft-ui-xaml/files/4585619/App207.zip)

**Actual behavior**
The NavView pane is shown expanded on on application start

**Expected behavior**
The NavView pane should be collapsed on application start

**Version Info**

NuGet package version: Microsoft.UI.Xaml 2.4.0

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |  |
| November 2019 Update (18363)  | yes   |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | yes|
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**
Originally reported on Windows Template Studio https://github.com/microsoft/WindowsTemplateStudio/issues/3644

### PR DESCRIPTION
**Pull request by Felix-Dev**
## Description
This PR fixes an issue where setting the `IsPaneOpen` property of the NavigationView to *false* before launching the NavigationView in the *Left* expanded state (either explicitly or via the `Auto` pane display mode) would have no effect (the pane is launched in an open state).

The updated behavior of the [NavigationView.IsPaneOpen](https://docs.microsoft.com/en-us/uwp/api/microsoft.ui.xaml.controls.navigationview.ispaneopen) API is the following on NavigationView launch:

| PaneDisplayMode | IsPaneOpen value | Pane will be opened | Remarks |
|-------------|-------------|-----|---|
| Auto | True | ❓ | If NavigationView is set into LeftMinimal/LeftCompact mode the pane will be launched in a closed state and IsPaneOpen will be set to false. If the NavigationView is set into Left mode the pane will be launched in an opened state |
| LeftMinimal | True | ❌| IsPaneOpen will be set to false |
| LeftCompact | True | ❌ | IsPaneOpen will be set to false |
| Left | True | ✔| - |
| Top | True | - | No pane to open |
| Auto | False| ❌ | Pane will be launched in a closed state for every app window width (*) |
| LeftMinimal | False| ❌| - |
| LeftCompact | False| ❌| - |
| Left | False| ❌| (*) |
| Top | False| - | No pane to open |

(*) = This behavior has been updated as part of this PR. The pane is now closed when `IsPaneOpen` is set to false and the pane is launched in Left expanded state (either explicitly or via the `Auto` display mode). All other configurations you see in the table above are the current behavior and unchanged by this PR.

Once this PR has been merged we should also consider providing this information about the PaneDisplayMode and IsPaneOpen API interplay on NavigationView launch on the [NavigationView.IsPaneOpen](https://docs.microsoft.com/en-us/uwp/api/microsoft.ui.xaml.controls.navigationview.ispaneopen) API documentation page (for example in a "Remarks" section) starting with whatever WinUI version will include this change. 

## Motivation and Context
Fixes #2391. 

## How Has This Been Tested?
Tested manually and added an API test.

## Additional Context
@YuliKl FYI.

### CODE REVIEW

**Comment by StephenLPeters** [comment]
I'd like @ojhad to weigh in, we had a conversation about this behavior during a debug session a few weeks ago. Do you remember the context of that conversation?

**Comment by ojhad** [comment]
> I'd like @ojhad to weigh in, we had a conversation about this behavior during a debug session a few weeks ago. Do you remember the context of that conversation?

If I remember correctly, we were launching into compact mode and that the pane was being forced into the closed state regardless of the `IsPaneOpen` property (which, according to above, seems like the intended behavior). 

However changing the `IsPaneOpen` property was causing different codepaths to get taken (hence the content dialog issue). When it was set to `true`, during setup, that value propagated to splitview which caused it to try add children to the popup root during measure.

**Comment by StephenLPeters** [comment]
@Felix-Dev The pipeline fix just went in, could you please merge master into this PR?

**Comment by Felix-Dev** [comment]
@StephenLPeters Merged with master.

**Review by StephenLPeters — APPROVED** [review]
:shipit:

**Pull request merged**
