### PR TITLE
Tweaks to Rainbow Backgrounds on CommandBarFlyout and MenuFlyout TestUI pages

### PR DESCRIPTION
**Pull request by mdtauk**
## Description
Tweaks to Rainbow Backgrounds on CommandBarFlyout and MenuFlyout TestUI pages

## Motivation and Context

Harder transitions added to the Rainbow Background help to illustrate the blurring from the Acrylic CommandBarFlyouts and MenuFlyouts.  This PR is being submitted at the suggestion of @StephenLPeters 
https://github.com/microsoft/microsoft-ui-xaml/issues/5213

_This is my second ever PR and submission to the repo so apologies if I have done something wrong_

## How Has This Been Tested?

I opened the pages in the MUXTestApp and observed the changes

## Screenshots (if appropriate):

image
image

### CODE REVIEW

**Review by chingucoding — APPROVED** [review]
This background looks really cool, great idea!

**Comment by mdtauk** [comment]
I missed that the CommandBar test page also used the rainbow background, so I have added that now

image

**Comment by StephenLPeters** [comment]
@mdtauk Can you merge in Main to pick up a recent infrasturcture fix that will unblock the pipeline?

**Comment by mdtauk** [comment]
> @mdtauk Can you merge in Main to pick up a recent infrasturcture fix that will unblock the pipeline?

@StephenLPeters  GitHub for Windows says it is merged with Main - is there something else I need to do?  I am relatively new to this.
image

**Review by karenbtlai — APPROVED** [review]

**Pull request merged**
