### PR TITLE
Introduce SettingsControls: SettingsCard, SettingsExpander, SettingsButton, SettingsGroup

### LINKED ISSUE #8146: Proposal: SettingsCard, SettingsExpander, SettingsButton, SettingsGroup
# Proposal: SettingsCard, SettingsExpander, SettingsButton, SettingsGroup

The new Windows 11 Settings app experience has gained a lot of approval and is used as the standard for many apps.

However, the implementation of each app is very different and the lack of these standard controls has frustrated developers having to create them again and again.

Toolkit Lab has already created some of those controls as a sample but it is not full control and so I decided to bring this conversation into here WinUI.

---

## Summary

| Name | Description |
| --- | --- |
| SettingsControls | General term of following controls |
| SettingsCard | Static settings control |
| SettingsExpander | Expandable settings control |
| SettingsGroup | Grouping settings control |
| SettingsButton | Clickable settings control |

### Naming validation

`SettingsControls` is valid naming because these controls are only used in settings pages or apps. `FormControls` #82 was valid for Windows 10 Settings control styles.

## Rationale

* There should be standard controls as I described in the top section
* It's already built in the community lab, but it's available in C# devs, not in C++ devs.

- SettingsCard: for obvious reasons
- SettingsExpander: for obvious reasons
- SettingsGroup: If you create these controls in code, They should be created all at once with group title
- SettingsButton: This control can be created by SettingsCard with the property IsClickable, but Card and Button will be used in different scenarios and so Card and Button should be separated.

## Scope

| Capability | Priority |
| :---------- | :------- |
| There should be standard of them | Must |
| Developers/users can use/see consistent UI control| Must |
| Creat SettingsCard/SettingsExpander | Must |
| Create SettingsGroup | Must |
| Create SettingsButton | Should |

### SettingsCard

Default
image

```xaml
<muxc:SettingsCard
    Icon="{StaticResource SampleIcon}"
    Header="Edit your color"
    Description="You can able to customize your color by picking color">

    <Button Content="Change" />

</muxc:SettingsCard>
```

Property|Type|Description
---|---|---
Header|String|
Description|String|
Icon|IconElement|
Content|Object|

### SettingsExpander

Expanded
image

Collapsed
image

Expanded, multiple SettingsExpanderItemCard, Footer
image

Expanded, multiple SettingsExpanderItemButton
image

```xaml
<muxc:SettingsExpander
    Icon="{StaticResource SampleIcon}"
    Title="App theme"
    Description="Select which app theme to display">

    <TextBlock Text="Dark" />

    <muxc:SettingsExpander.Items>
        <muxc:SettingsExpanderItemCard>
           <CheckBox IsTrue="True" />
        </muxc:SettingsExpanderItemCard>
        <muxc:SettingsExpanderItemButton Title="">
           <CheckBox IsTrue="True" />
        </muxc:SettingsExpanderItemButton>
    </muxc:SettingsExpander.Items>
</muxc:SettingsExpander>
```

Property|Type|Description
---|---|---
Header|String|
Description|String|
Icon|IconElement|
Content|Object|
Items|Object (list of SettingsCard)|
Footer|Object|

### SettingsButtons

Default
image

| Property | Type | Description |
| --- | --- | --- |
Header|String|
Description|String|
Icon|IconElement|
Content|Object|
Click event|event|

### SettingsGroup

Default
image

Property|Type|Description
---|---|---
Header|String|
Content|Object|

## Open Questions

- ~~Create SettingsCard with 'IsClickable' property and Remove SettingsButton~~
- ~~Name validation: Settings* or Form*~~

## References

- Official controls created for general use case by Microsoft
  - [MUXC.Expander](https://docs.microsoft.com/windows/winui/api/microsoft.ui.xaml.controls.expander)
  - [CommunityToolkitLabs.SettingsControl](https://github.com/CommunityToolkit/Labs-Windows/tree/main/labs/SettingsControls)
- Third party control libraries
  - [Richasy/ExpanderEx](https://github.com/Richasy/ExpanderEx)
  - [PowerToys.Setting.UI](https://github.com/microsoft/PowerToys/tree/main/src/settings-ui/Settings.UI/Controls/Setting)
  - [ghost1372/SettingsUI](https://github.com/ghost1372/SettingsUI)

### PR DESCRIPTION
**Pull request by onein528**
## Description

Introduce new controls, SettingsControls: SettingsCard, SettingsExpander, SettingsButton, SettingsGroup.

## Motivation and Context

Closes #8146

The new Windows 11 Settings app experience has gained a lot of approval and is used as the standard for many apps.

However, the implementation of each app is very different and the lack of these standard controls has frustrated developers having to create them again and again.

Toolkit Lab has already created some of those controls as a sample but it is not complete control and so I decided to bring this conversation into here WinUI.

## Tasks

- [ ] Add theme resources
- [ ] Add SettingsCard
- [ ] Add SettingsExpander
- [ ] Add SettingsButton
- [ ] Add SettingsGroup
- [ ] Add Interaction Tests
- [ ] Add UI Tests
- [ ] Add API Tests
- [ ] Add documentations

## How Has This Been Tested?

_Not yet_

## Screenshots (if appropriate):

_Not yet_

### CODE REVIEW

**Comment by onein528** [comment]
@microsoft-github-policy-service agree [company="5bfa"]

**Comment by onein528** [comment]
@microsoft-github-policy-service agree company="5bfa"

**Comment by onein528** [comment]
@microsoft-github-policy-service agree

**Comment by heartacker** [comment]
$$S(f) = \frac{1}{2}\sum_{k=-\infty}^{\infty}X(f-kf_c)$$

**Pull request closed without merging**
