### PR TITLE
Updated README.md to indicate Issue 1000 celebration

### PR DESCRIPTION
**Pull request by ryandemopoulos**

### CODE REVIEW

**Comment by mrlacey** [comment]
Not wanting to take anything away from the milestone, but `348 + 246 = 594`

_Note that the numbers GitHub assigns are shared by issues and pull requests._

image

**Comment by ryandemopoulos** [comment]
@mrlacey Good observation.  :)  Well, I kinda don't want to halt things now that I've already soft-announced that we'll do a drawing, so perhaps I might re-word the Readme.md update to acknowledge this.  One sec... I'll adjust it.

**Comment by ryandemopoulos** [comment]
@mrlacey OK, I updated the posting.  Let me know what you think--does this look better?  (we'll also send a tweet about this, so I'll make sure to use similar phraseology in the tweet)

**Comment by mdtauk** [comment]
The 1000th contribution perhaps, rather than _Issue_ specifically?

**Comment by ryandemopoulos** [comment]
@mdtauk I like "contributions"--good suggestion.  Just committed that change.  Hopefully this is good now.  :)  Appreciate the eyes on this.

**Pull request merged**
