### PR TITLE
Update comment

### PR DESCRIPTION
**Pull request by beervoley**
## Description

This PR adds a comment to the Pager resources requested by the translation team.

### CODE REVIEW

**Review by StephenLPeters — COMMENTED** [review]
I'd suggest something like.  The Pager allows the user to page in new content that is not currently in view.  The pager doesn't require scrolling.

**Comment by ranjeshj** [comment]
>   [Windows.UI.Xaml.Controls.AppBarToggleButton]

Curious why the master files need to change for this PR

---
Refers to: test/MUXControlsTestApp/verification/AppBarToggleButton-4.xml:16 in 413b522. [](commit_id = 413b522d4254328413328fb2d70e71890cb58b02, deletion_comment = False)

**Comment by beervoley** [comment]
> > [Windows.UI.Xaml.Controls.AppBarToggleButton]
> 
> Curious why the master files need to change for this PR
> 
> Refers to: test/MUXControlsTestApp/verification/AppBarToggleButton-4.xml:16 in [413b522](https://github.com/microsoft/microsoft-ui-xaml/commit/413b522d4254328413328fb2d70e71890cb58b02). [](commit_id = [413b522](https://github.com/microsoft/microsoft-ui-xaml/commit/413b522d4254328413328fb2d70e71890cb58b02), deletion_comment = False)

After merging master into this branch, pipeline failed due to failed visual tree verification test. This is the failed run: 
[link](https://github.com/microsoft/microsoft-ui-xaml/pull/3807/checks?check_run_id=1654158167)
Not sure why that happened - because the only change made in this PR is the comment.

**Review by ranjeshj — APPROVED** [review]

**Pull request merged**
