### PR TITLE
Remove explicit sizes of InfoBar

### LINKED ISSUE #3617: Bug: WinUI-2.5: Accessibility: [MAS1.4.4]: Action/Informational link text is getting truncated in Infobar tab content when TextScaling is applied to 200%
**Tags**
Accessibility, A11yFT,  A11yMAS, A11yMediumImpact, MAS1.4.4, Large Text, Sev3, WinUI-2.5, Win32, Wipro 

**User Impact**
People with Low vision are not able to identify the Action button/Informational link in Infobar canvas area.

**Steps to reproduce the bug**
Settings-->Display-->Set TextScaling to 200%

Launch the WinUI_2.5_TestApp

1. Go to 'Infobar' tab and activate it.
2. For 2nd type of Inforbar, set Action button to Button and Hyperlink
3. In Infobar, Action/Informational controls
4. But in Textscaling 200%, these two controls(Action/Informational) truncated.

**Expected behavior**
Action/Informational link text should visible properly in Infobar tab content, when TextScaling is applied to 200%.
 
**Actual behavior**
Action/Informational link text is getting truncated in Infobar tab content.
 
**Screenshots**
 
 
image

image

Version Info
Win32
Windows OS Version: Windows 10
App: WinUI_2.5_TestApp

### PR DESCRIPTION
**Pull request by chingucoding**
## Description

Removing the explicit setting of action button and hyperlink height in InfoBar as that prevents large text from getting rendered properly.
## Motivation and Context

Closes #3617
## How Has This Been Tested?

Tested manually.
## Screenshots (if appropriate):

Images of InfoBar with text scaling set to 225%:

Infobar with action button

Infobar with hyperlink

### CODE REVIEW

**Review by ranjeshj — APPROVED** [review]

**Comment by ranjeshj** [comment]
Thanks @chingucoding . Can you share a screenshot of 100% as well ?

**Comment by gabbybilka** [comment]
I'm going to clone and test however I believe that we also need to change the height and margin of the InfoBar to support the updated button height and keep everything centered.

**Comment by chingucoding** [comment]
Here are the 100% screenshots:

Infobar using 100% textscaling with button

Infobar using 100% textscaling with hyperlink

Should we set the min height of those to 24 to align them correctly?

**Comment by gabbybilka** [comment]
Hi @chingucoding, thank you for the screenshots! These screenshots you linked make it seem like the action buttons, especially the hyperlink aren't quite vertically centered. Could you try and fix that? Setting the height to be min 24 _might_ be the fix. Thank you!

**Comment by chingucoding** [comment]
Set the minheight to 24px now leaving us with centered button/hyperlink:

Infobar with centered button

Infobar with centered hyperink

**Comment by gabbybilka** [comment]
Looks good, thank you!

**Review by gabbybilka — APPROVED** [review]

**Comment by gabbybilka** [comment]
Actually, can we add in a StaticResource InfoBarActionButtonMinHeight for this value? @ranjeshj, do you agree? Thank you!

**Comment by chingucoding** [comment]
Good idea @gabbybilka ! I added two resources, InfoBarActionButtonMinHeight and InfoBarHyperlinkButtonMinHeight for this.

**Comment by ranjeshj** [comment]
@chingucoding  can you merge with master ?

**Comment by chingucoding** [comment]
Merged with master @ranjeshj .

**Pull request merged**
