### PR TITLE
Update references from 'master' branch to 'main' branch

### LINKED ISSUE #2676: Rename VisualTreeMaster and other usages of the word master
Since the word "master" is problematic for multiple reasons, most importantly because of its racist connotated history, we should try to find a neutral alternative.

Possible alternative names for "master" could be:
- main
- root
- primary

and similarly we could rename VisualTreeMaster to:
- VisualTreeMain
- VisualTreePrimary

### PR DESCRIPTION
**Pull request by kmahone**
The primary development branch in the repo was renamed from 'master' to 'main'. This PR updates the references to the branch in the various readme files, etc.. There are also a few scripts that needed to be updated to reference the main branch.

Closes #2676

### CODE REVIEW

**Comment by chingucoding** [comment]
Can you add "Closes #2676 " to the PR description?

**Review by ranjeshj — APPROVED** [review]
:shipit:

**Pull request merged**
