### PR TITLE
Fix SelectionModel SelectRange crash

### LINKED ISSUE #1984: SelectionModel.SelectRange throws with nested data
**Describe the bug**

`SelectionModel.SelectRange` throws with nested data (and even if it didn't I suspect the current logic is wrong or at least very confusing, see note below)

**Steps to reproduce the bug**

The following are unit test fragments in the MUXControls `SelectionModelTests.cs` file:

With a simple flat list, `Select()`-ing multiple items has the same behavior as `SelectRange()`. The following test passes:

```csharp
var data = new[] { 1, 2, 3 };
var target = new SelectionModel { Source = data };

target.Select(1);
target.Select(2);

ValidateSelection(
    target, 
    new List<IndexPath> { Path(1), Path(2) },
    new List<IndexPath>() { Path() });

target.ClearSelection();
target.SelectRange(Path(1), Path(2));

ValidateSelection(
    target,
    new List<IndexPath> { Path(1), Path(2) },
    new List<IndexPath>() { Path() });

```

With a nested selection, `SelectRange` throws:

```csharp
var data = CreateNestedData(3, 3, 2);
var target = new SelectionModel { Source = data };

target.Select(1);
target.Select(2);

ValidateSelection(
    target,
    new List<IndexPath> { Path(1), Path(2) },
    new List<IndexPath>() { Path() });

target.ClearSelection();
target.SelectRange(Path(1), Path(2));

ValidateSelection(
    target,
    new List<IndexPath> { Path(1), Path(2) },
    new List<IndexPath>() { Path() });
```

```
 Assert.Fail failed. Exception thrown by action on the UI thread: System.Runtime.InteropServices.COMException (0x8000000B): The operation attempted to access data outside the valid range
    
    invalid vector subscript
       at Microsoft.UI.Xaml.Controls.SelectionModel.SelectRange(IndexPath start, IndexPath end)
       at Windows.UI.Xaml.Tests.MUXControls.ApiTests.RepeaterTests.SelectionModelTests.<SelectRange_Should_Work>b__0_0()
       at MUXControlsTestApp.Utilities.RunOnUIThread.<>c__DisplayClass1_1.<Execute>b__1()
```

**Expected behavior**

Selecting 1 and 2 behaves the same as selecting the range 1..2.

**NOTE: even if this didn't throw I suspect the behavior would be different due to [this logic](https://github.com/microsoft/microsoft-ui-xaml/blob/49d724e1d9f77d9c29a86bc09b749c4ec2c8dd7c/dev/Repeater/SelectionModel.cpp#L727-L730) which is actually why I was testing this. IMO this logic is faulty because it makes selecting a range behave differently from selecting individual items**

**Screenshots**

**Version Info**

Current `master` (49d724e1)

NuGet package version: 

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2019 Update (18362)            | Yes   |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

### PR DESCRIPTION
**Pull request by chingucoding**
## Description

Add bound checking for selecting range using paths.
## Motivation and Context

Fixes #1984
## How Has This Been Tested?

Added new API test

### CODE REVIEW

**Comment by ranjeshj** [comment]
@grokys as FYI

**Comment by grokys** [comment]
Thanks! This does seem to fix the crash. The functionality I was trying to test for in the tests in #1984 is still IMO wrong or at least confusing, but I can open a new issue to discuss that.

**Pull request merged**
