### PR TITLE
Updating community call calendar invite

### PR DESCRIPTION
**Pull request by anawishnoff**
## Description
Updating the .ics calendar invite for this month's community call.

### CODE REVIEW

**Review by chingucoding — APPROVED** [review]

**Comment by StephenLPeters** [comment]
@anawishnoff what is the gh-pages branch this PR is getting merged into? I'm having trouble running the pipeline on this because its not being merged into master.

**Comment by anawishnoff** [comment]
@StephenLPeters gh-pages doesn't have any of the WinUI code on it, it just has the website code (html, css, js files). When I created the branch off of master I completely wiped out everything and just started from scratch to build the website on it.

**Comment by StephenLPeters** [comment]
@anawishnoff Can you just merge this change into GH-pages then (without using a pull request)?  It doesn't make sense to block this on the pipeline running, it wouldn't do anything anyway, and the pipeline is not set up to run on that branch.

**Review by ranjeshj — APPROVED** [review]

**Pull request merged**
