### PR TITLE
TeachingTip: Fix bug where empty title/subtitle was not respected in ApplyTemplate leading to gap

### LINKED ISSUE #1396: TeachingTip Title takes space even when there is no content.
When the tips Title content is set to null the remaining content still lays out as if there were text in the title.

### PR DESCRIPTION
**Pull request by chingucoding**
## Description

Add checks when in ApplyTemplate to collapse the textblocks if necessary.

## Motivation and Context

Closes #1396 
## How Has This Been Tested?

Add new API test

### CODE REVIEW

**Comment by StephenLPeters** [comment]
Go ahead and change the member variable name.

**Review by StephenLPeters — APPROVED** [review]

**Comment by chingucoding** [comment]
> Go ahead and change the member variable name.

Done :)

**Comment by chingucoding** [comment]
The test failure was a layout cycle issues which was caused by directly changing visibility of elements inside OnApplyTemplate. I switched to visual states for that now and updated the TeachingTip testhooks function to get the Title/Subtitle textblock through `GetTemplateChild` instead of requesting that once in OnApplyTemplate. That way, we are able to store two elements less inside the TeachingTip that aren't used beside the test hooks.

**Comment by zadjii-msft** [comment]
I'm looking forward to this landing so the Terminal can use this too - I don't think we're going to always need a TeachingTip with both a title and subtitle, so right now we always end up with some weird space. 

Hopefully we can see this land in 2021 ☺️

**Pull request merged**
