### PR TITLE
Revert AutoSuggestBox fix since it regressed TextBox wrapping scenario

### PR DESCRIPTION
**Pull request by ranjeshj**
https://github.com/microsoft/microsoft-ui-xaml/issues/3284

The fix was template binding ContentAlignment to Alignment and that changed the default horizontal alignment of TextBox from Stretch to Left. This ends up causing wrappable text boxes to wrap immediately instead of taking up available space.

@beervoley  as FYI

### CODE REVIEW

**Review by chingucoding — COMMENTED** [review]
Shouldn't it be enough to just revert the TextBox changes? iIRC, AutosuggestBox has it's own TextBox style so it shouldn't interfere with normal TextBox behaviour.

**Comment by beervoley** [comment]
> Shouldn't it be enough to just revert the TextBox changes? iIRC, AutosuggestBox has it's own TextBox style so it shouldn't interfere with normal TextBox behaviour.

@ranjeshj that's a good point. We can just revert the changes of the TextBox :)

**Review by beervoley — APPROVED** [review]

**Pull request merged**
