### PR TITLE
Revert the change to winuibuildagents

### PR DESCRIPTION
**Pull request by StephenLPeters**
We've had a number of strange lab build failure over the last few days, I'm reverting the winuiBuildAgents change to see if the issue is there.

### CODE REVIEW

**Comment by kmahone** [comment]
Instead of reverting everything, just update the yml files to switch the pool name back

**Comment by kmahone** [comment]
i.e. replace all instances of:
```
pool:  
  name: 'winuibuildagents'
```
with

```
pool:  
  name: 'windows-2019''
```

The rest of the changes don't need to be reverted.

**Comment by StephenLPeters** [comment]
looks like the build failures are not unique to the winui pool :/

**Comment by kmahone** [comment]
It looks like you reverted your entire change. So it still ran on winuibuildpool.

**Comment by kmahone** [comment]
Yuck. Sorry, I think you need to use 

`vmImage: 'windows-2019'`
instead of
`name: 'windows-2019'`

**Review by kmahone — APPROVED** [review]

**Pull request merged**
