### PR TITLE
Update Accent Colour Brushes to System APIs

### PR DESCRIPTION
**Pull request by karenbtlai**
## Description

- Update Accent Colour Brushes to System APIs
- Remove colour animations in RadioButtons and Slider that uses these Accent Color Brushes

### CODE REVIEW

**Comment by mdtauk** [comment]
Aren't the colours exposed as colours rather than brushes?

You can animate colours, but not brushes.

Is there a reason why the colour transitions are being removed?

https://docs.microsoft.com/en-us/windows/uwp/design/style/color#accent-color-palette

**Comment by ranjeshj** [comment]
> Aren't the Accent Shades/Tones exposed as colours rather than brushes?
> 
> You can animate colours, but not brushes.
> 
> Is there a reason why the colour transitions are being removed?
> 
> https://docs.microsoft.com/en-us/windows/uwp/design/style/color#accent-color-palette

I assume the issue is because we get system brushes but not colors ? @stmoy @YuliKl  This is unfortunate. Do we have colors we could use instead ?

**Comment by mdtauk** [comment]
> > Aren't the Accent Shades/Tones exposed as colours rather than brushes?
> > You can animate colours, but not brushes.
> > Is there a reason why the colour transitions are being removed?
> > https://docs.microsoft.com/en-us/windows/uwp/design/style/color#accent-color-palette
> 
> I assume the issue is because we get system brushes but not colors ? @stmoy @YuliKl This is unfortunate. Do we have colors we could use instead ?

The documentation page mentions
```You can also access the accent color palette programmatically with the UISettings.GetColorValue method and UIColorType enum.```

Also the XAML example shows the value being assigned as a Color to a SolidColorBrush
```Xaml
<Page.Resources>
    <ResourceDictionary>
        <ResourceDictionary.ThemeDictionaries>
            <ResourceDictionary x:Key="Light">
                <SolidColorBrush x:Key="ButtonBackground" Color="{ThemeResource SystemAccentColor}"/>
                <SolidColorBrush x:Key="ButtonBackgroundPointerOver" Color="{ThemeResource SystemAccentColorLight1}"/>
                <SolidColorBrush x:Key="ButtonBackgroundPressed" Color="{ThemeResource SystemAccentColorDark1}"/>
            </ResourceDictionary>
        </ResourceDictionary.ThemeDictionaries>
    </ResourceDictionary>
</Page.Resources>

<Button Content="Button"></Button>
```

**Comment by karenbtlai** [comment]
> > > Aren't the Accent Shades/Tones exposed as colours rather than brushes?
> > > You can animate colours, but not brushes.
> > > Is there a reason why the colour transitions are being removed?
> > > https://docs.microsoft.com/en-us/windows/uwp/design/style/color#accent-color-palette
> > 
> > 
> > I assume the issue is because we get system brushes but not colors ? @stmoy @YuliKl This is unfortunate. Do we have colors we could use instead ?
> 
> The documentation page mentions
> `You can also access the accent color palette programmatically with the UISettings.GetColorValue method and UIColorType enum.`
> 
> Also the XAML example shows the value being assigned as a Color to a SolidColorBrush
> 
> ```
> <Page.Resources>
>     <ResourceDictionary>
>         <ResourceDictionary.ThemeDictionaries>
>             <ResourceDictionary x:Key="Light">
>                 <SolidColorBrush x:Key="ButtonBackground" Color="{ThemeResource SystemAccentColor}"/>
>                 <SolidColorBrush x:Key="ButtonBackgroundPointerOver" Color="{ThemeResource SystemAccentColorLight1}"/>
>                 <SolidColorBrush x:Key="ButtonBackgroundPressed" Color="{ThemeResource SystemAccentColorDark1}"/>
>             </ResourceDictionary>
>         </ResourceDictionary.ThemeDictionaries>
>     </ResourceDictionary>
> </Page.Resources>
> 
> <Button Content="Button"></Button>
> ```

@mdtauk The resource is a Brush, and when accessed through ColorAnimation's `TargetProperty="(Panel.Background).(SolidColorBrush.Color)"` it becomes buggy and simply disappears. :(

**Comment by mdtauk** [comment]
Maybe this is something WinUI 3 can fix in the future.

**Comment by stmoy** [comment]
> The resource is a Brush, and when accessed through ColorAnimation's TargetProperty="(Panel.Background).(SolidColorBrush.Color)" it becomes buggy and simply disappears. :(

What does this mean? We use ColorAnimation in a few places; I wonder if there is bug here? I think @teaP had similar difficulties but worked around them somehow?

**Comment by mdtauk** [comment]
> > The resource is a Brush, and when accessed through ColorAnimation's TargetProperty="(Panel.Background).(SolidColorBrush.Color)" it becomes buggy and simply disappears. :(
> 
> What does this mean? We use ColorAnimation in a few places; I wonder if there is bug here? I think @teaP had similar difficulties but worked around them somehow?

You could probably generate colour resources using code to grab the colour from the brush, and generate a colour resource in the Theme ResourceDictionaries.

**Review by ranjeshj — APPROVED** [review]

**Pull request merged**
