### PR TITLE
Update gitignore for vscode

### PR DESCRIPTION
**Pull request by licanhua**
Copied from https://github.com/github/gitignore/blob/master/Global/VisualStudioCode.gitignore

### CODE REVIEW

**Comment by licanhua** [comment]
> Some of the files there are important, like the cpp configuration and settings.json. What specific files were you seeing get added that you didn't expect?
> I'm pretty sure at least c_cpp_properties.json needs to be included.
I already see a complain about .vscode/c_cpp_properties.json

**Comment by jevansaks** [comment]
> I already see a complain about .vscode/c_cpp_properties.json

Can you push that delta and show what it looks like?

**Comment by licanhua** [comment]
I don't think we need include .vscode/c_cpp_properties.json.  Here is an example 
```
      {
             "name": "Win32",
             "compilerPath": "",
-            "includePath": [
-                "${workspaceFolder}/dev/Collections",
-                "${workspaceFolder}/dev/Common",
-                "${workspaceFolder}/dev/dll",
-                "${workspaceFolder}/dev/inc",
-                "${workspaceFolder}/dev/TreeView",
-                "${workspaceFolder}/BuildOutput/Intermediates/Microsoft.UI.Xaml/obj/CppWinRT/Platform",
-                "${workspaceFolder}/BuildOutput/Intermediates/Microsoft.UI.Xaml/obj/CppWinRT/Component",
-                "${workspaceFolder}/BuildOutput/Intermediates/Microsoft.UI.Xaml/obj/CppWinRT/Component/winrt",
-                "${workspaceFolder}/BuildOutput/Intermediates/Microsoft.UI.Xaml/obj/CppWinRT/Component/Automation/Peers",
-                "${workspaceFolder}/BuildOutput/Intermediates/Microsoft.UI.Xaml/obj/CppWinRT/Component/Controls",
-                "${workspaceFolder}/BuildOutput/Intermediates/Microsoft.UI.Xaml/obj/CppWinRT/Component/Controls/Primitives",
-                "${workspaceFolder}/BuildOutput/Intermediates/Microsoft.UI.Xaml/obj/CppWinRT/Component/Media",
-                "${workspaceFolder}/BuildOutput/Intermediates/Microsoft.UI.Xaml/obj/CppWinRT/Component/Microsoft/UI/Composition/Effects",
-                "${workspaceFolder}/BuildOutput/Intermediates/Microsoft.UI.Xaml/obj/CppWinRT/Component/Microsoft/UI/Private/Controls",
-                "${workspaceFolder}/BuildOutput/Intermediates/Microsoft.UI.Xaml/obj/CppWinRT/Component/Microsoft/UI/Private/Media",
-                "${workspaceFolder}/BuildOutput/Intermediates/Microsoft.UI.Xaml/obj/CppWinRT/Component/XamlTypeInfo",
-                "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\VC\\Tools\\MSVC\\14.16.27023\\include",
-                "C:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.18323.0\\shared",
-                "C:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.18323.0\\um",
-                "C:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.18323.0\\winrt",
-                "C:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.18323.0\\ucrt",
-                "${workspaceFolder}/dev/Telemetry",
-                "${workspaceFolder}/dev/Repeater"
-            ],
+            "includePath": [],
             "defines": [],
             "browse": {
                 "path": [
-                    "${workspaceFolder}/dev",
-                    "${workspaceFolder}/idl",
-                    "${workspaceFolder}/test",
-                    "${workspaceFolder}/BuildOutput/Intermediates/Microsoft.UI.Xaml/obj/"
+                    "d:\\repo\\microsoft-ui-xaml\\*"
                 ],
                 "limitSymbolsToIncludedHeaders": true,
                 "databaseFilename": "${workspaceFolder}/.vscode/"
             },
-            "windowsSdkVersion": "10.0.18323.0",
-            "configurationProvider": "microsoft.vscode-nmake-tools",
-            "cppStandard": "c++17",
-            "intelliSenseMode": "msvc-x64"
+            "configurationProvider": "microsoft.vscode-nmake-tools"
         }
     ],
     "version": 4
```

**Comment by jevansaks** [comment]
It seems like your VS Code clobbered the one that I authored. I would like to have the cpp json file properly configured for VS Code because using it for browsing is very nice. Is your VS Code up to date? Do you have the Cpp intellisense plugin installed? Did you do anything manually to reset that file, perhaps?

**Comment by licanhua** [comment]
my vscode is latest version. I installed plugin like C/C++ intellisense, c# for visual studio code, Wave For VS code

**Comment by jevansaks** [comment]
Can you look into the settings.json configuration for Wave and see if there's a way to have that settings file be different than the one for the current project? It looks like Wave is clobbering the values I put somehow.

**Comment by licanhua** [comment]
I didn't see c_cpp_properties.json problem very recently. Close the pull request

**Pull request closed without merging**
