### PR TITLE
use old style by default

### PR DESCRIPTION
**Pull request by licanhua**
Use 2.5 style by default

### CODE REVIEW

**Comment by mdtauk** [comment]
How would you suggest we test the new visual styles?  I was running the ``token-experiment`` branch to do that, so will there be a branch with this setting changed to **Latest**?

**Comment by licanhua** [comment]
yes. you will need to change the testapp to use latest manually

**Comment by licanhua** [comment]
will take the change in merge feature/token-experiment with master branch

**Pull request closed without merging**
