### PR TITLE
[infra] Update verification files script to work with newer PWSH 7

### PR DESCRIPTION
**Pull request by chingucoding**
## Description

Scrpit didn't work on PWSH 7, now it does.
## How Has This Been Tested?

Tested manually.

### CODE REVIEW

**Comment by beervoley** [comment]
@chingucoding does it work on older PSWH versions tho?:)

**Comment by chingucoding** [comment]
> @chingucoding does it work on older PSWH versions tho?:)

Tested with the "standard" Windows 10 Powershell which is version 5.1.x and script still works fine :)

**Comment by beervoley** [comment]
@kmahone could you please have a look?

**Review by kmahone — APPROVED** [review]

**Pull request merged**
