### PR TITLE
Progress Ring Visual Update

### PR DESCRIPTION
**Pull request by karenbtlai**
## Description

- Set background track to transparent
- Set strokeThickness to 3px

## Screenshots (if appropriate):

image

### CODE REVIEW

**Comment by mdtauk** [comment]
I'm curious about the move to using 3px as a thickness, considering all the guidance and documentation uses 4px as the base measurement.

Has that guidance changed, or is it just not deemed necessary for these progress controls, and other paddings and margins that have been changed?

**Comment by karenbtlai** [comment]
> I'm curious about the move to using 3px as a thickness, considering all the guidance and documentation uses 4px as the base measurement.
> 
> Has that guidance changed, or is it just not deemed necessary for these progress controls, and other paddings and margins that have been changed?

Great question @mdtauk ! This update is simply according to design guidance, and I'm pretty curious as to why it's 3px rather than multiples of 4px. @chigy would you be able to explain this better?

**Review by marksfoster — APPROVED** [review]

**Comment by beervoley** [comment]
@karenbtlai the verification files you're updating are already in master :) they were merged today. can you please merge master before you merge this PR ?:)

**Pull request merged**
