### PR TITLE
Fix MUX CommandBar style not being applied to TextControl flyouts. 

### LINKED ISSUE #4472: TextBox context menu uses old design
image

When you right click in a TextBox or a derived control you get this menu, which has a design from before v2.2.

### PR DESCRIPTION
**Pull request by StephenLPeters**
Text Control Flyouts were referencing a TextCommandBarFlyout by static resource references. These resources were only defined in the system's Generic.xaml.  System xaml only has Windows.UI.Xaml.TextCommandBarFlyout which references Wux command bar flyout.  We need a MUX.TextCommandBarFlyout for these controls to have flyouts with our command bar flyout style updates. Thus we add these resources in XamlControlsResources.

Fixes #4472

### CODE REVIEW

**Review by ranjeshj — APPROVED** [review]
:shipit:

**Comment by ranjeshj** [comment]
@StephenLPeters  can you merge in master ?

**Comment by StephenLPeters** [comment]
image

**Pull request merged**
