### PR TITLE
update intellisense file

### PR DESCRIPTION
**Pull request by ranjeshj**
update intellisense file

### CODE REVIEW

**Comment by jevansaks** [comment]
>     <member name="P:Microsoft.UI.Xaml.Controls.NumberBox.TextAlignmentProperty" />

Where did this go?

---
Refers to: build/NuSpecs/Intellisense/Microsoft.UI.Xaml.xml:2132 in f76126a. [](commit_id = f76126a1b80c2d2189b607284d95434cafd59f6e, deletion_comment = True)

**Comment by jevansaks** [comment]
>     <member name="T:Microsoft.UI.Xaml.Controls.FlowLayout" />

Is this intentionally removed?

---
Refers to: build/NuSpecs/Intellisense/Microsoft.UI.Xaml.xml:759 in f76126a. [](commit_id = f76126a1b80c2d2189b607284d95434cafd59f6e, deletion_comment = True)

**Comment by jevansaks** [comment]
>     <member name="T:Microsoft.UI.Xaml.Controls.Primitives.ZoomSnapPoint" />

all the scroller stuff seems gone

---
Refers to: build/NuSpecs/Intellisense/Microsoft.UI.Xaml.xml:3111 in f76126a. [](commit_id = f76126a1b80c2d2189b607284d95434cafd59f6e, deletion_comment = True)

**Comment by jevansaks** [comment]
>     <member name="T:Microsoft.UI.Xaml.Controls.StylesVersion" />

this is gone now

---
Refers to: build/NuSpecs/Intellisense/Microsoft.UI.Xaml.xml:3973 in f76126a. [](commit_id = f76126a1b80c2d2189b607284d95434cafd59f6e, deletion_comment = False)

**Review by jevansaks — APPROVED** [review]
:shipit:

**Comment by ranjeshj** [comment]
> > ```
> > <member name="P:Microsoft.UI.Xaml.Controls.NumberBox.TextAlignmentProperty" />
> > ```
> 
> Where did this go?
> 
> Refers to: build/NuSpecs/Intellisense/Microsoft.UI.Xaml.xml:2132 in [f76126a](https://github.com/microsoft/microsoft-ui-xaml/commit/f76126a1b80c2d2189b607284d95434cafd59f6e). [](commit_id = [f76126a](https://github.com/microsoft/microsoft-ui-xaml/commit/f76126a1b80c2d2189b607284d95434cafd59f6e), deletion_comment = True)

These seem to be preview types. Following up.

**Pull request merged**
