### PR TITLE
Merge feature/cbs to main

### PR DESCRIPTION
**Pull request by kmahone**

### CODE REVIEW

**Review by jevansaks — APPROVED** [review]
:shipit:

**Review by ranjeshj — APPROVED** [review]

**Review by StephenLPeters — APPROVED** [review]

**Review by chingucoding — COMMENTED** [review]
Out of curiosity, @kmahone did you use the generate new projects scripts and did they help and work as expected?

**Comment by kmahone** [comment]
> Out of curiosity, @kmahone did you use the generate new projects scripts and did they help and work as expected?

@jevansaks was the one who created the new projects. Jevan: did you use these scripts?

**Comment by jevansaks** [comment]
> Out of curiosity, @kmahone did you use the generate new projects scripts and did they help and work as expected?

I don't remember! I think I looked into it and I didn't because I needed to create a project in the Materials subfolder so I ended up just copying one of the existing projects and modifying it.

**Pull request merged**
