### PR TITLE
Removed Duplicate resources for TopNavigationViewItem style brushes

### LINKED ISSUE #5869: Duplicate resources for TopNavigationViewItem style brushes
**Describe the bug**
Three TopNavViewItem resources are defined twice in NavigationView_rs1_themeresources.xaml, with different values in Light theme:
* TopNavigationViewItemBackgroundPointerOver
* TopNavigationViewItemBackgroundPointerOver
* TopNavigationViewItemBackgroundSelected

**Steps to reproduce the bug**

1. Open \dev\NavigationView\NavigationView_rs1_themeresources.xaml
2. Observe TopNavViewItem resources list above in Dark and Light theme dictionaries.

**Expected behavior**
Resources should be defined once.

**Screenshots**

**Version Info**
Latest main

NuGet package version: 

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  |  |

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2021 Update (19043)            |    |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |  |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

### PR DESCRIPTION
**Pull request by aqibbanday**
## Description
I have removed the duplicate resources as mentioned in the following issue
https://github.com/microsoft/microsoft-ui-xaml/issues/5869

## Motivation and Context
Removed duplicate resources present in \dev\NavigationView\NavigationView_rs1_themeresources.xaml
https://github.com/microsoft/microsoft-ui-xaml/issues/5869
"Closes #5869"

## How Has This Been Tested?
Tested by running the MUXControlsTestApp>NavigationView>Top Mode Tests
No Change in behavior detected.

### CODE REVIEW

**Comment by aqibbanday** [comment]
> @aqibbanday There are lots of change in this PR which seem to be unrelated to the issue we are trying to fix here. Can you remove the unrelated changes ?

Its seems, XAML styler has added indentation to few XAML files. No breaking change.
I can remove it if required.

**Comment by aqibbanday** [comment]
@ranjeshj Hi, I have reverted extra changes made, this is the final commit: https://github.com/microsoft/microsoft-ui-xaml/pull/5910/commits/66460168dce9b59fe0bf3a34013549d43bdf523d

**Review by StephenLPeters — APPROVED** [review]

**Review by ranjeshj — APPROVED** [review]

**Pull request merged**
