### PR TITLE
Update AnimatedVisualSources with adjustments from design.

### PR DESCRIPTION
**Pull request by StephenLPeters**
Slightly new designs for the down chevrons and the settings icon.

### CODE REVIEW

**Comment by mdtauk** [comment]
The Search Icon still has a slight opacity issue where the handle overlaps.

image

**Comment by StephenLPeters** [comment]
> The Search Icon still has a slight opacity issue where the handle overlaps.
> 
> image

That's true, but we are going to leave this as is for now.  At a normal icon's size this is very hard to see.  We should open an issue to address this when our designers have more time though.

**Review by ranjeshj — APPROVED** [review]

**Pull request merged**
