### PR TITLE
Update visual tree verification infra to get rid of the term "master"

### PR DESCRIPTION
**Pull request by chingucoding**
## Description

Update documentation, CI scripts and testing code to use new names instead of "master".
## Motivation and Context

#2676 
## How Has This Been Tested?

Ran tests

### CODE REVIEW

**Comment by StephenLPeters** [comment]
@chingucoding have you tested updating the visual verification reference files after this change?

**Comment by chingucoding** [comment]
> @chingucoding have you tested updating the visual verification reference files after this change?

I have not tested updating file from the CI. Also we would probably need new screen shots for those since they don't have the new folder name.

**Comment by chingucoding** [comment]
@StephenLPeters Should I revert my changes to the documentation and let #2650 include those changes to prevent merge conflicts? @Felix-Dev Would you be fine with that?

**Comment by Felix-Dev** [comment]
@chingucoding I'm fine with merge your changes into my PR and fix any occuring merge conflicts in the developer documentation file (and update it accordingly to use the new term where I added content).

**Comment by StephenLPeters** [comment]
> > @chingucoding have you tested updating the visual verification reference files after this change?
> 
> I have not tested updating file from the CI. Also we would probably need new screen shots for those since they don't have the new folder name.

Does this have to be done in a subsequent checkin or can we do it atomically?

**Comment by chingucoding** [comment]
> > I have not tested updating file from the CI. Also we would probably need new screen shots for those since they don't have the new folder name.
> Does this have to be done in a subsequent checkin or can we do it atomically?

Since there are no visual tree verification updates, and the only screenshot right now is the azure artifacts view I don't have access too, there is no screenshot I can update here. If someone with access to the azure directory can provide a screenshot for the updated "microsoft employee" view, we can update it with this PR. However currently the "VisualTree" folder is not present in the drop since there were no changes to the visual tree verification files.

**Comment by chingucoding** [comment]
However since #2660 also introduces new screenshots that also need to be updated, we could also do it with that PR is @Felix-Dev is fine with that.

**Comment by StephenLPeters** [comment]
> However since #2660 also introduces new screenshots that also need to be updated, we could also do it with that PR is @Felix-Dev is fine with that.

@chingucoding and @Felix-Dev how should we progress with merging in this and #2660?  I think merging this and updating #2660 would make sense?

**Comment by Felix-Dev** [comment]
@StephenLPeters Yes, we can merge this into master first and then update #2660 accordingly.

**Pull request merged**
