### PR TITLE
Clarifying point on rounded corners

### LINKED ISSUE #3330: Question: What 'Rounded corners' are not going to be in WinUI 3.0?
In the latest [roadmap](https://github.com/microsoft/microsoft-ui-xaml/blob/master/docs/roadmap.md#winui-30-feature-roadmap), What rounding corners are you talking about?

image
image

If this is rounded-corners for all controls like border, grid, etc. (or CornerRadius property usage in styles) it's going to be a problem. I expect this really is talking about popups or window corners?

### PR DESCRIPTION
**Pull request by anawishnoff**
## Description
There was customer confusion about what exactly rounded corners refers to in the feature roadmap, this PR fixes that.

Closes #3330.

### CODE REVIEW

**Review by chingucoding — APPROVED** [review]
:shipit:

**Comment by chingucoding** [comment]
@anawishnoff I think you can add "Closes #3330" in the PR description at this clarifies what was meant with the corner radius.

**Review by StephenLPeters — APPROVED** [review]

**Comment by Poopooracoocoo** [comment]
hi. sorry for commenting on a totally unrelated issue but could one of you _please_ take a look at issue 1530?

**Pull request merged**
