### PR TITLE
Fix TreeView single selection

### PR DESCRIPTION
**Pull request by kaiguo**
## Description

In single select mode, TreeView relies on ListView's built in behavior to unselect the previous item and select the new one. However the unselect sometimes doesn't happen if previous selected item is out of view. 

Added a check in UpdateSelection to clear the previous selection if ListView doesn't do it.

## Motivation and Context

Fixes 2) in #1756

### CODE REVIEW

**Comment by kaiguo** [comment]
> Is there a test for this already existing or do we need an new test for this bug? 😅

The bug wasn't 100% repro so I didn't add test. But I think you are right, it's always better to have something exercising the scenario, I'll add test 😀.

**Comment by StephenLPeters** [comment]
>     if (auto treeView = AncestorTreeView())

It feels like this logic should be happening in TreeView, not TreeViewItem.  TreeViewItem could just inform anyone who cares, like TreeView, that it should be selected. Then TreeView could handle the single selection case appropriately.  Perhaps this isn't the place to change the relationship between TreeView and TreeViewItem though


---
Refers to: dev/TreeView/TreeViewItem.cpp:436 in 749ad7a. [](commit_id = 749ad7acde6c864eef4f35806d0959d791067353, deletion_comment = False)

**Comment by StephenLPeters** [comment]
Because of the test retry logic I think it will be difficult to make a valuable test if the repro is not consistent.  For instance, if your repro happens 20% of the time and a subsequent change removed this product fix entirely, our test infrastructure would only report a failure 3.28% of the time. So if you are going to write a test I think its important that its repro rate be close to 50% at least.  @LukeLongly @RanjeshJ I wonder if we should add a meta data flag that would allow us to change the threshold at which we report a test failure. That way if we have an inconsistent repro we could set the test to report any failure and these tests would be more likely to catch a product issue.

---
In reply to: [569366655](https://github.com/microsoft/microsoft-ui-xaml/pull/1799#issuecomment-569366655) [](ancestors = 569366655)

**Comment by ranjeshj** [comment]
Do we understand why this is not a consistent repro ?

**Comment by chingucoding** [comment]
Sorry if this is a stupid idea, but couldn't we just put tests for issue that don't trigger reliably in a for loop and run them multiple times?

**Comment by kaiguo** [comment]
> Do we understand why this is not a consistent repro ? 

I think it's virtualization related, if the previous selected item is unrealized and not in view, ListView sometimes won't trigger selection change event on the previous item when making a new selection.

**Comment by ranjeshj** [comment]
> > Do we understand why this is not a consistent repro ?
> 
> I think it's virtualization related, if the previous selected item is unrealized and not in view, ListView sometimes won't trigger selection change event on the previous item when making a new selection.

I see. Perhaps for now we could do what @chingucoding suggests and run the test in a loop a couple of times and hope that it fails more consistently if this regresses.

**Comment by kaiguo** [comment]
> I see. Perhaps for now we could do what @chingucoding suggests and run the test in a loop a couple of times and hope that it fails more consistently if this regresses.

Yeah I'll wrap it in a for loop then.

**Pull request merged**
