### PR TITLE
Fix NavigationView light dismiss issue

### LINKED ISSUE #2208: NavigationView: Pane light dismiss does not adjust item width
**Describe the bug**
When light dimissing the NavigationView pane in left display mode, the NavigationViewItems widths are not adjusted to now match the new width of the closed pane. This causes UI issues especially for *NavigationViewItemSeparators* as they are not applying their *right* margin to the new width of the collapsed pane. Please the see the following gif for illustration:

navviewpane_issue

**Expected behavior**
NavigationViewItems should work with the correct pane width when the pane is light dismissed:
image

**Version Info**
NuGet package version: 
2.4.0-prerelease.200322001

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| November 2019 Update (18363)  | Yes  |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |  Yes  |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**
I would like to fix this.

### PR DESCRIPTION
**Pull request by Felix-Dev**
## Description
Fixes the NavigationView light dismiss issue where the NavigationViewItems would not work with the correct closed pane width.

#### Implementation details 
I removed the check if the navigation pane (a SplitView pane) is closed. When we close the pane using the pane toggle button (or set SplitView.IsPaneOpen to false), we were already entering the *ListSizeCompact* visual state. In other words, splitView.IsPaneOpen() returned *false*. However, if the pane was light dismissed, splitView.IsPaneOpen() returned *true* at this point, thus not entering the *ListSizeCompact* visual state, causing the issue to manifest. 
Now that the check is removed, we enter this visual state no matter how the navigation pane is closed . And since we are only calling this code in a handler for the event when the pane is closing (OnSplitViewPaneClosing) having removed this check should not introduce any other side-effects.

## Motivation and Context
Fixes #2208 

## How Has This Been Tested?
Tested visually.

## Screenshots
See the following GIF:

navviewpane_issue_fix

### CODE REVIEW

**Comment by Felix-Dev** [comment]
@chingucoding Good point. Added an interaction test now.

**Comment by ranjeshj** [comment]
@Felix-Dev can you please merge with master which includes some stability fixes for the PR pipeline ?

**Comment by Felix-Dev** [comment]
@ranjeshj Done.

**Pull request merged**
