### PR TITLE
Convert bug template issue template to an issue form

### PR DESCRIPTION
**Pull request by chrisglein**
## Description
Convert the bug issue template markdown to [GitHub's new issue forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms). I only converted the bug template form for now, but all of them can be converted.

## Motivation and Context
Get more structured data from issues logged against the repo. Dropdowns, required fields, etc.

## How Has This Been Tested?
In a fork, pushed to that fork's main branch. [Try it out yourself](https://github.com/chrisglein/microsoft-ui-xaml/issues/new/choose)

## Screenshots (if appropriate):
image

### CODE REVIEW

**Review by chingucoding — APPROVED** [review]
That is soooo cool, thank you for making this change!

**Comment by ranjeshj** [comment]
Thanks @chrisglein ! 
Can we also add the nuget package version which looks like is missing in the updated form ? 
NuGet package version:

**Comment by chrisglein** [comment]
> Thanks @chrisglein !
> Can we also add the nuget package version which looks like is missing in the updated form ?
> NuGet package version:
> Examples
> [Microsoft.UI.Xaml 2.4.0]
> [Microsoft.UI.Xaml 2.5.0]
> [Microsoft.UI.Xaml.2.6.0-prerelease.210430001]
> [Microsoft.UI.Xaml 2.6.0]
> [Microsoft.WinUI 3.0.0-preview4.210210.4]
> [WinUI 3 - Project Reunion 0.5 Preview: 0.5.0-prerelease]
> [WinUI 3 - Project Reunion 0.5: 0.5.0]
> [WinUI 3 - Project Reunion 0.5: 0.5.7]
> [WinUI 3 - Project Reunion 0.8 Preview: 0.8.0-preview]
> [WinUI 3 - Windows App SDK 0.8: 0.8.0] If you're seeing your issue in older previews of WinUI 3, please try this release.

Easy peasy. Done!

**Review by ranjeshj — APPROVED** [review]

**Pull request merged**
