### PR TITLE
Fix #5768

### LINKED ISSUE #5768: WinUI 2.6.X/2.7.X cause the submission to MSStore failure with error code 1201 (Only in Windows Application Packaging Project with FullTrustProcess)
**Describe the bug**
Failed to submit the package to Microsoft Store if an UWP App is Windows Application Packaging Project with fullTrustProcess.
Once you submit your package. Microsoft Store will report "Attention needed" after a few minutes. Error code is 1201

Someone report the same issue [here](https://github.com/microsoft/microsoft-ui-xaml/issues/5262#issuecomment-904993749)

**Steps to reproduce the bug**
1. Create a Windows Application Packaging Project with UWP project and .Net Framework project
2. Install WinUI 2.6.X or WinUI 2.7.0preview
3. Publish and submit to MSStore

**Expected behavior**
Pass the certification and should not report 1201

**Screenshots**
image

**Version Info**
Encountered issue in:
[Microsoft.UI.Xaml 2.6.1]
[Microsoft.UI.Xaml 2.6.2]
[Microsoft.UI.Xaml 2.7.0-preview]

Disappear in:
[Microsoft.UI.Xaml 2.5.0]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2021 Update (19043)            | Yes   |
| October 2020 Update (19042)        | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
  | Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**
None

### PR DESCRIPTION
**Pull request by crramirez**
## Description
As I understand from comment https://github.com/microsoft/microsoft-ui-xaml/issues/5768#issuecomment-934659178 this is what needs to be done

## Motivation and Context
Fixes #5768

## How Has This Been Tested?
Made the change manually as the comment https://github.com/microsoft/microsoft-ui-xaml/issues/5768#issuecomment-935542510

### CODE REVIEW

**Comment by crramirez** [comment]
Could you please add the **hacktoberfest-accepted** label to this PR?

**Comment by asklar** [comment]
@StephenLPeters @llongley   which nuget package version is this in?

**Comment by StephenLPeters** [comment]
We have not made a release or prerelease with this change in it yet.

**Pull request merged**
