### PR TITLE
Fix Deprecated icons

### LINKED ISSUE #8375: Deprecated icons used through-out the code!
### Describe the bug

As Microsoft has declared icon codes ranging E0** - E5** as deprecated (1) who-knows-how-long-ago, Microsoft should follow their own rules. Yet, up till now, there are loads of icon codes used in the repo. This is mostly notable in CJK context, where these icons show as "garbled chinese" characters. I've seen cases of people showing this bad UI even in the search bar in Windows Explorer. One of the most "core" things of Windows!

1) Message

### Steps to reproduce the bug

it's the code

### Screenshots

image

### Additional context

| old icon | appearance     | new icon |
|----------|----------------|----------|
| E001    | ✔ | E73E      |
| 10A      | ✖              |          |
|          |                | 8BB ~close~    |
|          |                | 947 ~multiply~ |
|          | →              | 894 clear    |
|          |                | 711 ~cancel~   |
| 052      | 👁       | F78D |
| 26B      | chev.R.small | 970      |
| 26C      | chev.L.small | 96F      |
| 0E2      | chev.L       | 76B      |
| 0E3      | chev.R       | 76C      |
| 0E4      | chev.U       | 70E      |
| 0E5      | chev.D       | 70D      |
| 094,11A  | 🔎       | 721     |
| 00B      | 🖤   | B52      |
| 115      | ⚙     | 713      |

### PR DESCRIPTION
**Pull request by Jay-o-Way**
## Description

| old icon | appearance     | new icon |
|----------|----------------|----------|
| E001    | ✔ | E73E      |
| E10A      | ✖              | E894         |
| E052      | 👁       | F78D |
| E26B      | chev.R.small | E970      |
| E26C      | chev.L.small | E96F      |
| E0E2      | chev.L       | E76B      |
| E0E3      | chev.R       | E76C      |
| E0E4      | chev.U       | 70E      |
| E0E5      | chev.D       | E70D      |
| E11A  | 🔎       | E721     |
| E00B      | 🖤   | EB52      |
| E115      | ⚙     | E713      |

Appended Icon Changes:

| old icon | appearance     | new icon |
|----------|----------------|----------|
| E0B8 |    | N/A No apt replacement |
| E0E7 |    | E73E |
| E10C |    | E712 |
| E193 |    | E7E6 |
| E228 |    | E96E

## Motivation and Context

They have been deprecated for years now.

Fixes: #8375 and #7350

- https://github.com/microsoft/microsoft-ui-xaml/issues/6390
- https://github.com/microsoft/microsoft-ui-xaml/issues/7139

and many more, like

- https://github.com/microsoft/microsoft-ui-xaml/issues/6392
- https://github.com/microsoft/PowerToys/issues/25284
- https://github.com/microsoft/PowerToys/issues/21267
- https://github.com/microsoft/microsoft-ui-xaml/issues/7850
- https://github.com/microsoft/WinUI-Gallery/issues/1128

### CODE REVIEW

**Comment by Jay-o-Way** [comment]
FYI @crutkas, @StephenLPeters and others

**Comment by Jay-o-Way** [comment]
@pratikone any luck finding somebody?

**Comment by Jay-o-Way** [comment]
Anybody home?

**Comment by karkarl** [comment]
Hey @Jay-o-Way thanks so much for filing the bug and submitting the fix. I'm currently verifying with the designers to make sure these are apt replacements for the glyphs, as well as trying to identify how this regression happened in the first place...

**Comment by Jay-o-Way** [comment]
Thanks @karkarl . Same idea applies to the SymbolIcon application. Translating `Icon="Settings` to the actual icon code. Do you know where we can find that?

**Comment by Jay-o-Way** [comment]
Any progress?

And, after this would be merged, when would the effects be visible? Any _eta_? First the next version of this source needs to be released, then every app should update to use that new version. I imagine that takes quite some time...

**Comment by Jay-o-Way** [comment]
What's taking so long? I can't stand this!

**Comment by karkarl** [comment]
> @karkarl Any progress?
> 
> And, after this would be merged, when would the effects be visible? Any _eta_? First the next version of this source needs to be released, then apps (and don't forget the OS!) should update to use that new version. I imagine that takes quite some time...

After some investigation, here is what is happening with the icons: 

Both Segoe MDL2 (Windows 10 icon font) and Segoe Fluent Icons (Windows 11 icon font) use the Unicode private use area (PUA) to encode icons. Some Chinese fonts encode Chinese characters in the PUA range. PUA range goes from Unicode E000-F8FF. Some simplified Chinese apps are reporting these issues. The only font that has Chinese characters in that lower PUA range is a font intended for Hong Kong (Mingliu_HKSCS).

image


To avoid these codepoint collisions, it is recommended to use glyphs higher in range. Hence the note specified here: https://learn.microsoft.com/en-us/windows/apps/design/style/segoe-ui-symbol-font

>Glyphs with prefixes ranging from E0- to E5- (e.g. E001, E5B1) are currently marked as legacy and are therefore deprecated.

Note that these glyph ranges are not really "deprecated" in the traditional sense (misleading doc). The icons are still encoded and left intact. Unfortunately, this also means that should fonts start encoding in the higher PUA ranges, more collisions like this can still occur. 

It still makes sense for us to update the glyphs, hence here are the next steps from our side:
- Merge your PR, then figure out servicing schedule for this fix.
- Port changes into WinUI3 (servicing is approved)
- Update changes to Symbol enum - this is a breaking change thus requires formal API reviews
- Investigate the potential regression and prevent future codepoint collisions - why the app fonts are overwriting the icon fonts.

**Comment by kmahone** [comment]
There is an issue in the validation Pipeline building from forks. So I've merged this into a local user branch and will merge it to main from there.

**Comment by kmahone** [comment]
See #8576

**Comment by kmahone** [comment]
This is now merged to main. Thanks @Jay-o-Way for the fix.

**Comment by Jay-o-Way** [comment]
That's great news! Thanks, and special thanks to @karkarl for digging in to this. Looks like quite alot of work went into it. And this is not even the end of the line.

**Pull request merged**
