### PR TITLE
[ContentDialog] Add missing visibility setter for V2 style

### LINKED ISSUE #5713: ContentDialog occupies space in a StackPanel
**Describe the bug**
When putting ContentDialog in a StackPanel, it occupies vertical and horizontal space when it shouldn't. This happens exclusively with controls resources version 2

**Steps to reproduce the bug**
1. Add WinUI 2.6 to a blank app
2. Replace the placeholder Grid with the following in MainPage
   ```xaml
   <StackPanel>
       <ContentDialog />
       <Button>This should be at the top-right</Button>
   </StackPanel>
   ```

**Expected behavior**
The ContentDialog should not take any vertical space in the StackPanel

**Screenshots**
Good behavior, no WinUI installed
image

Good behavior, WinUI 2.6 and controls resource version 1
image

Bad behavior, WinUI 2.6 and controls resource version 2
image

**Version Info**

NuGet package version: 
[Microsoft.UI.Xaml 2.6.1]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes | Yes (system XAML islands) |

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (22000.132)              | Yes   |
| May 2021 Update (19043)            |    |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**
Same happens when the StackPanel uses Horizontal layout

### PR DESCRIPTION
**Pull request by chingucoding**
## Description

Adds a missing Visibility setter that would make ContentDIalog take up space in layouts even when not opened.
## Motivation and Context

Closes #5713 
## How Has This Been Tested?

Tested manually

### CODE REVIEW

**Comment by karenbtlai** [comment]
@chingucoding Can you update the visual verification files?

**Comment by chingucoding** [comment]
Unfortunately, the last build has already been deleted. Manually trying to figure out the difference was too difficult. Could we rerun the test run?

**Review by karenbtlai — APPROVED** [review]

**Pull request merged**
