### PR TITLE
Fix solution file entries

### PR DESCRIPTION
**Pull request by chingucoding**
## Description

Fixes the following solution view:

Image showing pipspager not in the right position in solution view hierarchy

## Motivation and Context

Fixes the misaligned solution-view of MUXControls
## How Has This Been Tested?

Tested manually:

Image showing solutionview of muxcontrol.sln

### CODE REVIEW

**Comment by beervoley** [comment]
@chingucoding could you please also include these changes in this PR:
image

**Comment by chingucoding** [comment]
Sure thing @beervoley , added them now.

**Review by beervoley — APPROVED** [review]

**Pull request merged**
