### PR TITLE
TeachingTip: Fix background for light-dismissable tip

### PR DESCRIPTION
**Pull request by Felix-Dev**
## Description
This PR fixes two background issues for a light-dismissable TeachingTip: 
* TeachingTip's Content UI background did not use transient background (regression)
* TeachingTip's HeroContent UI background did not use transient background

## Motivation and Context
Fixes https://github.com/microsoft/microsoft-ui-xaml/issues/3436

## How Has This Been Tested?
Tested visually and extended API test.

## Screenshots:
```xml
<muxc:TeachingTip Title="Title" Subtitle="Subtitle"
              IsLightDismissEnabled="True">
    <muxc:TeachingTip.HeroContent>
        <Rectangle Fill="Transparent" Width="100" Height="70" />
    </muxc:TeachingTip.HeroContent>
    <TextBlock Text="Extra Content" Margin="0,10,0,0"/>
</muxc:TeachingTip>
```
image

### CODE REVIEW

**Comment by chingucoding** [comment]
So with light dismiss, the `Background` property gets ignored by the "main" area of the TeachingTip. This should either be documented or background should be respected regardless if the TeachingTip is in lightdismiss-mode.

**Comment by Felix-Dev** [comment]
One way to go here would be to apply the `TeachingTipTransientBackground` theme resource only if no `Background` property is set. If `Background` is set, it will take precendence. Generally speaking, I'm in favor of respecting existing APIs whenever possible.

This will likely require adding code behind though as we won't be able to do that purely in XAML markup as of now.

**Comment by chingucoding** [comment]
Yes, unfortunately, this is nothing we can do without code behind. Given that this isn't the first time where we needed this, having a converter for this might be the better approach here. Though, a converter would of course break the lightweight styling aspect as bindings don't get reevaluated in users apps.

**Comment by StephenLPeters** [comment]
@Felix-Dev can you pull master into this branch to pickup the pipeline stability change that went in today? If you could do the same for your other PR's that would be great (I'm sorry they aren't getting the attention they deserve :( )

**Comment by Felix-Dev** [comment]
@StephenLPeters Done for my most recent PRs and some older ones. I am still holding out merging with master for my older PRs adding interaction tests (like https://github.com/microsoft/microsoft-ui-xaml/pull/3137) since that would for now block me locally from running interaction tests again (until PR https://github.com/microsoft/microsoft-ui-xaml/pull/3359 has been merged).

I can bring those few PRs up-to-date though in case you want to take a look at the downlevel/test pipeline test failures and don't want to wait for PR #3359.

**Comment by Felix-Dev** [comment]
Merged with master. We can try starting the test pipeline again (failed to run the previous time). @StephenLPeters FYI.

**Comment by StephenLPeters** [comment]
> So with light dismiss, the `Background` property gets ignored by the "main" area of the TeachingTip. This should either be documented or background should be respected regardless if the TeachingTip is in lightdismiss-mode.

We already do this for ContentRootGrid, I think we can make this change as is and should it be needed look at a way to fix this behavior.

**Review by StephenLPeters — APPROVED** [review]
:shipit:

**Pull request merged**
