### PR TITLE
ProgressBar, PersonPicture, and MTC Updates

### PR DESCRIPTION
**Pull request by karenbtlai**
## Description

Miscellaneous fixes:
- Update ProgressBarIndicator width for IndeterminatePaused and IndeterminateError
- Update badge control on PersonPicture
- Add Min/Max Width on MediaTransportControls

### CODE REVIEW

**Comment by llongley** [comment]
@karenbtlai FYI, this run failed because of an infra issue that I've resolved - try merging from main and re-running.

**Review by ranjeshj — APPROVED** [review]

**Pull request merged**
