### PR TITLE
Roadmap broken link

### PR DESCRIPTION
**Pull request by arpadbarta**
The link for the VS Templates in the roadmap is outdated.

## Description
Fixes a broken link in the roadmap.md file which should lead to the Win UI templates.

### CODE REVIEW

**Review by chingucoding — APPROVED** [review]

**Comment by StephenLPeters** [comment]
@anawishnoff FYI

**Review by StephenLPeters — APPROVED** [review]

**Comment by anawishnoff** [comment]
Thanks @arpadbarta! Looks good.

**Comment by arpadbarta** [comment]
> Thanks @arpadbarta! Looks good.

No worries, I'm happy if I can help!

**Pull request merged**
