### PR TITLE
Text/RichEditBox: Fix binding issue with foreground

### LINKED ISSUE #4470: TextBox & RichEditBox: Foreground reset on hovering
**Describe the bug**

When setting foreground on a TextBox, hovering over it will set the texts color to the default instead of the foreground.

**Steps to reproduce the bug**

1. Create TextBox
2. Type text into it
3. Unfocus, hover over it

**Expected behavior**

Foreground should be applied correctly
**Screenshots**

Gif showing foreground resetting when hovering over textbox.
**Version Info**

NuGet package version: 

Built repository.

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (19043)              | Yes  |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

### PR DESCRIPTION
**Pull request by chingucoding**
## Description

Adds missing binding.
## Motivation and Context

Closes #4470 
## How Has This Been Tested?

Tested manually.

### CODE REVIEW

**Review by StephenLPeters — APPROVED** [review]
:shipit:

**Comment by StephenLPeters** [comment]
@codendone is this change appropriate for RichTextBox?

**Comment by StephenLPeters** [comment]
@chingucoding does textblock have the same issue?

**Comment by chingucoding** [comment]
@StephenLPeters TextBlock does not suffer from this bug.

**Comment by codendone** [comment]
I don't understand why this fix was needed. The Foreground property inherits, so as long as an intermediate element isn't overriding the Foreground to a value which this element wants to ignore, this should be the same result.

What was the broken scenario?

**Comment by StephenLPeters** [comment]
> I don't understand why this fix was needed. The Foreground property inherits, so as long as an intermediate element isn't overriding the Foreground to a value which this element wants to ignore, this should be the same result.
> 
> What was the broken scenario?

@codendone you can see the issue here: https://github.com/microsoft/microsoft-ui-xaml/issues/4470  The visual state manager sets the foreground property on in the PointerOver state but when we enter the Normal state we don't revert to the same foreground color.  Looking at the tempalte, I can't explain why that is the case... it looks like it should return the foreground property to the default value (null?) which should then receive the propogated value from the parent.  Maybe the foreground property propogation doesn't work with VSM returning the value to null?

**Pull request merged**
