### PR TITLE
Rework dark theme TextBox and RichEditBox

### LINKED ISSUE #142: TextBox/RichEditBox Shouldn't Force Light Theme on Focus
**Describe the bug**
Both `TextBox` and `RichEditText` include a visual state like this:
```xml
<VisualState x:Name="Focused">
    <ObjectAnimationUsingKeyFrames Storyboard.TargetName="ContentElement" Storyboard.TargetProperty="RequestedTheme">
        <DiscreteObjectKeyFrame KeyTime="0" Value="Light" />
    </ObjectAnimationUsingKeyFrames>
</VisualState>
```

This interferes with lightweight styling, most notably when trying to theme the editor to _remain dark_ in a dark theme.

**Steps to reproduce the bug**
1. New UWP Application
2. Use this XAML for the main page (modify the `x:Class` to match your project)

```xml
<Page x:Class="App6.MainPage"
      xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
      xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
      Background="{ThemeResource ApplicationPageBackgroundThemeBrush}"
      RequestedTheme="Dark">

    <Grid>
        <Grid.Resources>
            <SolidColorBrush x:Key="TextControlBackground" Color="Transparent" />
            <SolidColorBrush x:Key="TextControlBackgroundPointerOver" Color="Transparent" />
            <SolidColorBrush x:Key="TextControlBackgroundFocused" Color="{ThemeResource SystemAltHighColor}" />
            <SolidColorBrush x:Key="TextControlForegoundFocused" Color="{ThemeResource SystemBaseHighColor}" />
        </Grid.Resources>
        
        <TextBox Text="Here is some text that I want to edit in a dark editor" FontSize="30"
                 TextWrapping="Wrap" />
    </Grid>
</Page>
```

**Expected behavior**
I expect the TextBox to use `SystemBaseHighColor` from the dark theme, but it resolves to the Light theme instead. Even worse, `TextControlBackgroundFocused` resolves to dark because its theme _isn't_ changed in the `Style`.

**Screenshots**
Screenshot showing the dark text (with some text selected in order to show that text exists)
image

### PR DESCRIPTION
**Pull request by chingucoding**
## Description

This PR switches the light mode upon focus to dark mode for a dark themed TextBox, RichEditBox and AutoSuggestBox.

## Motivation and Context

Closes #142

## How Has This Been Tested?

Tested manually using MUXControlsTestApp

## Screenshots (if appropriate):

Dark theme
darkmode-textbox

High contrast black
darkmode-textbox-highcontrast-black

High contrast #1
darkmode-textbox-highcontrast-1

High contrast #2
darkmode-textbox-highcontrast-2

### CODE REVIEW

**Comment by StephenLPeters** [comment]
@chingucoding could you pull master into this branch? I think the pipeline failure fix got merged in after this changed.

**Comment by chingucoding** [comment]
@StephenLPeters Done

**Comment by chingucoding** [comment]
@StephenLPeters @kmahone Do you have any ideas, what could have caused that failure? Should I pull and merge master in this branch again?

**Comment by robloo** [comment]
This is so cool to see coming to a close. This styling was one of the first 'quirks' in UWP I noticed switching over from WPF that just didn't seem right. It's great this is finally being closed. @chingucoding you are awesome to spend the time improving things like this!!

**Comment by chingucoding** [comment]
That was also something that was a bit unusual in UWP. Luckily we seem to be able to change this now!

PS: Thank you for your kind words @robloo 😄

**Comment by chigy** [comment]
@chingucoding , did you test this change on Editable Combobox?

**Comment by chingucoding** [comment]
@chigy Editable ComboBox also works:

editable-combobox-darkmode

Numberbox also works correctly

**Comment by Gavin-Williams** [comment]
This is still happening in the default WinUI 3 RichEditBox;

**Comment by StephenLPeters** [comment]
> This is still happening in the default WinUI 3 RichEditBox;
> 
> #2953

@llongley which version of winui 2 is in the winui3 preview?

**Comment by ranjeshj** [comment]
2.4.2

**Comment by StephenLPeters** [comment]
> 2.4.2

So this fix should be in the winui3 preview 2. @Gavin-Williams To confirm, you were using preview 2 correct?

**Pull request merged**
