### PR TITLE
TabView: Visual update

### PR DESCRIPTION
**Pull request by teaP**
This is mostly a visual update based on design comps. Colors and margins changed slightly; the + button now looks like a mini tab. I also added TabItemsChanged events, which hooked up to ListView.Items.VectorChanged, and hid keyboard accelerator tooltips.

### CODE REVIEW

**Comment by jevansaks** [comment]
Can you share before/after screenshots of the changes?

**Comment by mdtauk** [comment]
Could you also share the design comp that you are working towards?

**Comment by teaP** [comment]
> Could you also share the design comp that you are working towards?

Sure, here is the figma link:
https://www.figma.com/file/9OcpPKyRbLzCFIhNh2AWIi/Window-Tab-Exp

**Comment by mdtauk** [comment]
@teaP  the Figma files are internal only, so can't be viewed publically.

**Comment by teaP** [comment]
Here's a screenshot.
image
I'm not sure how to share the comps, then.

**Comment by adrientetar** [comment]
It looks a bit odd that the separator is cutting into the contour of the hovered tab imo 🤔 FWIW what Chrome does is fade out the separators around the tab when hovering it.

**Comment by adrientetar** [comment]
@stmoy Thanks, another question: why the TabItems property isn't just named Tabs or Items? TabView.TabItems makes it seem like there's another *Items property under TabView.

**Pull request merged**
