### PR TITLE
VisualTreeUtils: Improved API consistency, code cleanup

### PR DESCRIPTION
**Pull request by Felix-Dev**
## Description
[As discussed](https://github.com/microsoft/microsoft-ui-xaml/pull/3082#pullrequestreview-463810609) in PR https://github.com/microsoft/microsoft-ui-xaml/pull/3082 this PR aims to improve the API surface of the WinUI internal`VisualTreeUtils` class. Namely the following:

* Naming consistency: `FindElementOfTypeInSubtree()` has been renamed to `FindVisualChildByType()`
* Parameter consistency: `FindVisualChildByName()` now takes a `DependencyObject` as argument just like `FindVisualChildByType()` (including matching parameter name)
* Method call consistency: `FindVisualChildByName()` is now an extension method just like `FindVisualChildByType()`
* Internal code cleanup: Pattern matching, more compact code,...

Originally, I had planned to make this PR only after PR https://github.com/microsoft/microsoft-ui-xaml/pull/3082 had been merged into master but unfortunately, that PR might take some more time due to as of yet unresolved test failures. I don't want to have this work item waiting until then.

#### Important
Once this PR has been merged into master, any open PR adding new `FindElementOfTypeInSubtree()` calls needs to merge with master first. As far as I can tell though, no currently open PR *not* authored by me (I made a note for my PRs - if required) adds new calls to `FindElementOfTypeInSubtree()` right now.

### CODE REVIEW

**Review by StephenLPeters — APPROVED** [review]

**Comment by chingucoding** [comment]
Looks like Helix and the AppbarButton visual tree verification test seem to be the reason for the test failure (again). In multiple PRs, the AppbarButton visual tree verification file seemed to have caused this or at least show up in the "files that need to be changed" list. Should we disable that specific test until we figured out why this keeps coming up?

**Comment by StephenLPeters** [comment]
This PR #3446 should fix this issue for this and many other of the pipeline failures.

**Comment by robloo** [comment]
@Felix-Dev This also relates to the old discussion in  #1331. Perhaps the two topics could be merged together and both addressed by this PR.

**Comment by ranjeshj** [comment]
> @Felix-Dev This also relates to the old discussion in #1331. Perhaps the two topics could be merged together and both addressed by this PR.

This is a test infrastructure/code update as opposed to #1331 which is feature request for the platform.

**Pull request merged**
