### PR TITLE
Added similar issues bot

### PR DESCRIPTION
**Pull request by craigloewen-msft**
## Summary of the Pull Request

Creates a new GitHub action that makes a bot that will automatically comment on new issues letting them know about similarly titled issues using AI. Will look like this:

image

## Detailed Description of the Pull Request / Additional comments

The bot code is [open sourced here](https://github.com/craigloewen-msft/GitGudSimilarIssues). 

## Validation Steps Performed

Validated on other repos. You can manually validate queries like so: 
https://gitgudissues.azurewebsites.net/api/getsimilarissues/microsoft/microsoft-ui-xaml/window%20caption%20brushes%20not%20working

### CODE REVIEW

**Comment by riverar** [comment]
The bot response indicates prioritization occurs via thumbs up, but the team [has not indicated](https://github.com/microsoft/microsoft-ui-xaml/pull/8761) they are prioritizing community issues in that manner. Is this a commitment to start doing so or is this just boilerplate text that needs to be revised?

**Comment by craigloewen-msft** [comment]
@riverar this is boilerplate text that is used just for this bot.

**Review by Redth — APPROVED** [review]

**Comment by riverar** [comment]
Sounds good. I expect to see changes to the YAML to reflect that!

```diff
    steps:
      - name: Add comment
        run: gh issue comment "$NUMBER" --repo "$REPO" --body "$BODY"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NUMBER: ${{ github.event.issue.number }}
          REPO: ${{ github.repository }}
-         BODY: ${{ needs.getsimilarissues.outputs.message }}
```

**Comment by craigloewen-msft** [comment]
@riverar it's been added here: https://github.com/craigloewen-msft/GitGudSimilarIssues/blob/31ca2bdeece539a74f42fb0a9e4c25c71bf3627a/action.yml#L20

@Redth seems like merging is blocked despite approval? Please let me know if there's anything else you need from me to help merge this. THank you!

**Comment by riverar** [comment]
@craigloewen-msft Right and like mentioned above, the text is wrong. There's no thumbs-based voting here. So this PR needs to reflect alternate text.

**Comment by craigloewen-msft** [comment]
@riverar modified the comment body to edit out that part.

**Comment by riverar** [comment]
Looks good to me!

**Review by riverar — APPROVED** [review]

**Comment by bpulliam** [comment]
Separate issue opened for broken links #9159

**Pull request merged**
