### PR TITLE
NavigationView: Add missing top navigation brushes

### LINKED ISSUE #4515: NavigationView Invalid Theme Resources
**Describe the bug**
WinUI 2.5
https://github.com/microsoft/microsoft-ui-xaml/blob/7b55398026652cc95e82d96dc5be1aae3ee1204f/dev/NavigationView/NavigationView_rs1_themeresources.xaml#L63-L75

This should be rather:
```xaml
            <StaticResource x:Key="TopNavigationViewItemForeground" ResourceKey="TextFillColorSecondaryBrush" />
            <StaticResource x:Key="TopNavigationViewItemForegroundPointerOver" ResourceKey="TextFillColorPrimaryBrush" />
            <StaticResource x:Key="TopNavigationViewItemForegroundPressed" ResourceKey="TextFillColorPrimaryBrush" />
            <StaticResource x:Key="TopNavigationViewItemForegroundDisabled" ResourceKey="TextFillColorDisabledBrush" />
            <StaticResource x:Key="TopNavigationViewItemBackgroundPointerOver" ResourceKey="SubtleFillColorTransparentBrush" />
            <StaticResource x:Key="TopNavigationViewItemBackgroundPressed" ResourceKey="SubtleFillColorTransparentBrush" />
            <StaticResource x:Key="TopNavigationViewItemBackgroundSelected" ResourceKey="SubtleFillColorTransparentBrush" />
            <StaticResource x:Key="TopNavigationViewItemForegroundSelected" ResourceKey="TextFillColorPrimaryBrush" />
            <StaticResource x:Key="TopNavigationViewItemForegroundSelectedPointerOver" ResourceKey="TextFillColorSecondaryBrush" />
            <StaticResource x:Key="TopNavigationViewItemForegroundSelectedPressed" ResourceKey="TextFillColorTertiaryBrush" />
            <StaticResource x:Key="TopNavigationViewItemBackgroundSelectedPointerOver" ResourceKey="SubtleFillColorTransparentBrush" />
            <StaticResource x:Key="TopNavigationViewItemBackgroundSelectedPressed" ResourceKey="SubtleFillColorTransparentBrush" />
```

I've removed the last entry and added `Selected` to the remaining last two entries. Currently you cannot style the background of a selected item hover effect.

I did not open a PR, as the new/correct themeresources must also be applied in the corresponding template, and I am not that deep into the code. It should be easy though.

### PR DESCRIPTION
**Pull request by chingucoding**
## Description

Add dedicated brushes for selected top nav items.
## Motivation and Context

Closes #4515
## How Has This Been Tested?

Tested manually.

### CODE REVIEW

**Comment by ranjeshj** [comment]
@karenbtlai can you take a look since you are also touching the navview styles.

**Review by StephenLPeters — APPROVED** [review]

**Comment by karenbtlai** [comment]
> Oh if there is an ongoing PR for NavigationView, i can wait and look at the merge conflicts. Should have checked beforehand, sorry about this.

Thanks for the fix! If you can wait until after to avoid merge conflicts that will be great :)

**Comment by chingucoding** [comment]
> Thanks for the fix! If you can wait until after to avoid merge conflicts that will be great :)

Sure thing, I'll wait :)

**Review by karenbtlai — APPROVED** [review]

**Review by marksfoster — APPROVED** [review]

**Comment by karenbtlai** [comment]
@chingucoding the NavigationView PR is merged in. Would you be able to resolve the conflicts and get this in? Thanks in advance!

**Comment by chingucoding** [comment]
Merged now @karenbtlai !

**Pull request merged**
