### PR TITLE
Fix ring ColorSpectrum border

### PR DESCRIPTION
**Pull request by gabrielconl**
The border had a margin that caused it to be misaligned.
Before / after:
colorpickerbefore colorpickerafter

### CODE REVIEW

**Comment by llongley** [comment]
@gabrielconl @ranjeshj FYI, this run failed because of an infra issue that I've resolved - try merging from main and then we can re-run the PR build/test run.

**Comment by StephenLPeters** [comment]
@gabrielconl this one as well

**Review by StephenLPeters — APPROVED** [review]

**Pull request merged**
