### PR TITLE
Fixes TabView bottom border line is too short #5954

### LINKED ISSUE #5954: [Fix proposed] TabView bottom border line is too short
**Describe the bug**
TabView bottom border line is too short in new styles

**Screenshots**
image

### PR DESCRIPTION
**Pull request by eugenegff**
Fixes #5954

### CODE REVIEW

**Comment by beervoley** [comment]
@eugenegff could you please attach screenshots so we can verify the appearance?
With/without footer, with/without header :)

**Comment by eugenegff** [comment]
> @eugenegff could you please attach screenshots so we can verify the appearance? With/without footer, with/without header :)

Before fix
image

After fix
image

**Comment by eugenegff** [comment]
Before fix with header and footer
image

**Comment by eugenegff** [comment]
Before fix without header and footer
image

**Comment by eugenegff** [comment]
I added TabViewHeader to one of test UI pages so that anybody could make such screenshots easily

**Comment by beervoley** [comment]
> I added TabViewHeader to one of test UI pages so that anybody could make such screenshots easily - third screenshot is with this modification.

I believe that it will mess with a lot of tests that use that particular TabView for verification.

If you want to add an example, then it would be a good idea of adding another TabView :)

**Comment by eugenegff** [comment]
You right, I did not realize that this project was used for automated tests. Will force push only actual fix for the problem, removing modifications to test project

**Comment by eugenegff** [comment]
##[error]The nuget command failed with exit code(1) and error(Failed to download package 'runtime.win10-x64-aot.runtime.native.System.IO.Compression.4.0.1' from 'https://pkgs.dev.azure.com/ms/66f07283-7714-4cbf-be8f-73dfb782cfdc/_packaging/1ea232aa-2b5d-4b2d-a163-a803b8f889db/nuget/v3/flat2/runtime.win10-x64-aot.runtime.native.system.io.compression/4.0.1/runtime.win10-x64-aot.runtime.native.system.io.compression.4.0.1.nupkg'.

**Comment by beervoley** [comment]
I see this little issue:
image
the left arc is not full attached to the TabContainer. Is that some other changes you're playing with that are not in this PR?

**Comment by beervoley** [comment]
@eugenegff  after #5994 and #5993 are checked in, please merge the updated **main** to fix the test issues we're running into.

**Comment by eugenegff** [comment]
> I see this little issue:
> image
> the left arc is not full attached to the TabContainer as well as some part of the TabContainer border is visible where it shouldn't be. Is that some other changes you're playing with that are not in this PR?

This is separate, unrelated issue. May be later, after merging current PR.

**Comment by eugenegff** [comment]
> @eugenegff after #5994 and #5993 are checked in, please merge the updated **main** to fix the test issues we're running into.

done

**Comment by eugenegff** [comment]
> I see this little issue: image the left arc is not full attached to the TabContainer as well as some part of the TabContainer border is visible where it shouldn't be. Is that some other changes you're playing with that are not in this PR?

It is separate, unrelated issue, stock TabView has it when scale is 150%, you can see it in XamlControlsGallery yourself.

 I have fix for this issue too, but not sure, should I make separate PR or add it to the current one. Actually everything is so slow with contributions to MUX, so I don't want to slowdown this PR with additional fixes for much less important unrelated issue.

**Comment by beervoley** [comment]
> > I see this little issue: image the left arc is not full attached to the TabContainer as well as some part of the TabContainer border is visible where it shouldn't be. Is that some other changes you're playing with that are not in this PR?
> 
> It is separate, unrelated issue, stock TabView has it when scale is 150%, you can see it in XamlControlsGallery yourself.
> 
> I have fix for this issue too, but not sure, should I make separate PR or add it to the current one. Actually everything is so slow with contributions to MUX, so I don't want to slowdown this PR with additional fixes for much less important unrelated issue. With me being on the other side of the Earth, latency is 1 day for each our interaction.

Please, submit it as a separate PR.

**Review by beervoley — APPROVED** [review]

**Comment by eugenegff** [comment]
> > > I see this little issue: image the left arc is not full attached to the TabContainer as well as some part of the TabContainer border is visible where it shouldn't be. Is that some other changes you're playing with that are not in this PR?
> > 
> > 
> > It is separate, unrelated issue, stock TabView has it when scale is 150%, you can see it in XamlControlsGallery yourself.
> > I have fix for this issue too, but not sure, should I make separate PR or add it to the current one. Actually everything is so slow with contributions to MUX, so I don't want to slowdown this PR with additional fixes for much less important unrelated issue. With me being on the other side of the Earth, latency is 1 day for each our interaction.
> 
> Please, submit it as a separate PR.

https://github.com/microsoft/microsoft-ui-xaml/pull/6001

**Comment by beervoley** [comment]
@eugenegff thanks for the fix!! 
@ranjeshj checked in now

**Pull request merged**
