### PR TITLE
Fix TeachingTip getting stuck closed

### PR DESCRIPTION
**Pull request by StephenLPeters**
It was possible to set a teaching tip's IsOpen property to true while the closing animation is playing. This could cause the teaching tip to get in a state where IsOpen is true but it isn't displayed on screen. To work around this you would need to programmatically close and then reopen the tip. To fix this we can ignore IsOpen property changes while there are active animations.

### CODE REVIEW

**Review by RBrid — APPROVED** [review]

**Comment by harvinders** [comment]
@StephenLPeters Can we expect this to land in WinAppSDK 1.1 ?

**Pull request merged**
