### PR TITLE
Make testapp default style to latest

### PR DESCRIPTION
**Pull request by licanhua**
Not ready for review yet

### CODE REVIEW

**Review by ranjeshj — APPROVED** [review]

**Comment by chingucoding** [comment]
Is there any documentation on how to switch the styles when developing? I wasn't able to find anything in the docs folder.

**Comment by mdtauk** [comment]
> Is there any documentation on how to switch the styles when developing? I wasn't able to find anything in the docs folder.

I change a line of code in two files, I have no idea if its the correct way.

I would assume WinUI 2.5 would be branched off and use the older styles, and newer builds using `Latest`

**Comment by chingucoding** [comment]
> I change a line of code in two files, I have no idea if its the correct way.

I had to search for the correct files too and changed it in weird places but not sure if that was the best way either.

> I would assume WinUI 2.5 would be branched off and use the older styles, and newer builds using Latest

Isn't the idea that we have those two styles side by side in one branch with separate files?

**Comment by ranjeshj** [comment]
> > Is there any documentation on how to switch the styles when developing? I wasn't able to find anything in the docs folder.
> 
> I change a line of code in two files, I have no idea if its the correct way.
> 
> I would assume WinUI 2.5 would be branched off and use the older styles, and newer builds using `Latest`

```<XamlControlsResources Version="Latest" />``` should give you the new set of styles. Note that this is still very much work in progress.

**Pull request merged**
