### PR TITLE
Update ApplicationPageBackgroundThemeBrush

### PR DESCRIPTION
**Pull request by beervoley**
Update ApplicationPageBackgroundThemeBrush
## Description

This PR updates **ApplicationPageBackgroundThemeBrush** to use **SolidBackgroundFillColorBase** (to FF202020 in dark theme, FFF3F3F3 in light theme)

### CODE REVIEW

**Review by ranjeshj — APPROVED** [review]

**Comment by ranjeshj** [comment]
@YuliKl  as FYI

**Comment by karenbtlai** [comment]
@ranjeshj @YuliKl @beervoley this is a duplicate of `DefaultApplicationBackgroundThemeBrush`. Furthermore, the default background defined in the specs is `SolidBackgroundFillColorTertiaryBrush` which is #F9F9F9.

**Comment by mdtauk** [comment]
YAY!  This will finally mean the end of Pure Black and Pure White for window backgrounds.

#920 #921

**Comment by YuliKl** [comment]
> @ranjeshj @YuliKl @beervoley this is a duplicate of `DefaultApplicationBackgroundThemeBrush`. Furthermore, the default background defined in the specs is `SolidBackgroundFillColorTertiaryBrush` which is #F9F9F9?

@karenbtlai `ApplicationPageBackgroundThemeBrush` is an older brush from generic.xaml which appears as the default Page background color in the VS UWP app template. We need to change the values of that resource to stop defaulting to pure black/white. And I had checked with design, several times, that the hex values @beervoley listed in the description are correct for  the page background.

I'm not sure what this means for `DefaultApplicationBackgroundThemeBrush` - that might be a brush we no longer need?

**Comment by karenbtlai** [comment]
> > @ranjeshj @YuliKl @beervoley this is a duplicate of `DefaultApplicationBackgroundThemeBrush`. Furthermore, the default background defined in the specs is `SolidBackgroundFillColorTertiaryBrush` which is #F9F9F9?
> 
> @karenbtlai `ApplicationPageBackgroundThemeBrush` is an older brush from generic.xaml which appears as the default Page background color in the VS UWP app template. We need to change the values of that resource to stop defaulting to pure black/white. And I had checked with design, several times, that the hex values @beervoley listed in the description are correct for the page background.
> 
> I'm not sure what this means for `DefaultApplicationBackgroundThemeBrush` - that might be a brush we no longer need?

I see :) let's remove the duplicate brush then?

**Pull request merged**
