### PR TITLE
Moving PipsPager project into dev folder

### PR DESCRIPTION
**Pull request by RBrid**
Moving the PipsPager project inside the dev folder like any other control.

### CODE REVIEW

**Comment by chingucoding** [comment]
#4080 fixes the solution entries in addition to fixing a missing testui project entry, so I think it's better to close this in favor of #4080

**Comment by beervoley** [comment]
> #4080 fixes the solution entries in addition to fixing a missing testui project entry, so I think it's better to close this in favor of #4080

@RBrid yup, [this PR](https://github.com/microsoft/microsoft-ui-xaml/pull/4080) fixes the same and also adds the PipsPager tests to the shared tests : ) We just have to choose 1

**Comment by RBrid** [comment]
Sweet. Closing then. Thanks.

**Pull request closed without merging**
