### PR TITLE
Make tab corner overlays update colors

### PR DESCRIPTION
**Pull request by gabrielconl**
Fixes microsoft/terminal#7133

Tab corners only got colored when the tab was created, now they get updated together with the rest of the tab.

### CODE REVIEW

**Review by karenbtlai — APPROVED** [review]

**Comment by karenbtlai** [comment]
There's a pipeline regression, can you pull from main for the workaround?

**Comment by gabrielconl** [comment]
I think I did it, does it work now?

**Comment by gabrielconl** [comment]
The tests failed to download the sdk. Can you re-run them?

**Comment by gabrielconl** [comment]
@ranjeshj This PR should be ready to merge, but there was a problem with the tests themselves last time. Could you run them again?

**Comment by StephenLPeters** [comment]
@gabrielconl can you please merge main into your branch to pick up an infrastructure update?

**Comment by gabrielconl** [comment]
@StephenLPeters could this be backported to 2.6? Terminal would've liked to have that bug fixed.

**Pull request merged**
