### PR TITLE
AutoSuggestBox: Switch to lightweightstyling resource for icon fontsize

### LINKED ISSUE #3968: Increasing the FontSize of AutoSuggestBox should not increases the size of the Cancel icon as well
**Describe the bug**
Increasing the font size of AutoSuggestBox increases the size of the Cancel (X) icon, however the QueryIcon size is not changed.

**Steps to reproduce the bug**
```
<AutoSuggestBox FontSize="32" QueryIcon="Find"/>
```
**Expected behavior**
QueryIcon should also scale up

**Screenshots**

**Version Info**

NuGet package version: Microsoft.UI.Xaml 2.5.0

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |  |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

### PR DESCRIPTION
**Pull request by chingucoding**
## Description

Switch to usage of AutoSuggestBoxIconFontSize for the fontsize of the glyphelement to allow customization.

## Motivation and Context

Closes #3968
## How Has This Been Tested?

Tested manually

### CODE REVIEW

**Comment by mdtauk** [comment]
Are there any others that are missing?  PasswordBox Reveal Icon?  SearchBox Icon?

And speaking of the SearchBox, will the icon remain on the right, or move to the left to match FluentUI and Edge?

**Comment by chingucoding** [comment]
> Are there any others that are missing? PasswordBox Reveal Icon? SearchBox Icon?

Good point, if the team approves, I'll gladly add corresponding resources for the other controls too.

**Review by ranjeshj — APPROVED** [review]

**Comment by StephenLPeters** [comment]
Yeah, if there are other examples of icons behaving incorrectly we should fix those as well.  For this one, the query icon and close icon now use the same resource correct? Should they have separate knobs?

**Comment by chingucoding** [comment]
> For this one, the query icon and close icon now use the same resource correct? Should they have separate knobs?

They use the same one right now. Would be good to know if there is a use case where you want to have them different sizes. My fear is that this would just cause an inconsistent UI so I'm not sure if that's a good idea.

@mdtauk I've updated other controls to also expose a lightweight styling resource controlling the icons font size.

**Pull request merged**
