### PR TITLE
Add SplitButton accessibility test

### PR DESCRIPTION
**Pull request by chingucoding**
## Description

Adding accessibility tests for the SplitButton control. Also fixing A11y issues found on the way.
## Motivation and Context

Increase A11y test coverage

### CODE REVIEW

**Comment by mdtauk** [comment]
Will there be any consideration for how this control behaves in Touch interactions.  It only brings up the menu from the chevron, rather than allowing the action of the button to be performed.

I can understand this may be desired, but maybe you could add the command that the button would normally perform, to the flyout automatically?

The biggest example of this for me, is the Restart button in Windows Update on Windows 11 - which requires me to go to the Start Menu to restart, as the button only displays the flyout.

**Comment by chingucoding** [comment]
@mdtauk This is indeed valuable feedback, this PR however will be part of a demo and will be closed soon after :)

@karenbtlai Could we rerun the pipeline?

**Comment by chingucoding** [comment]
Closing now since this PR was for the demo and fulfilled it's purpose.

**Pull request closed without merging**
