### PR TITLE
Add F# to list of .NET languages

### PR DESCRIPTION
**Pull request by JaggerJo**

### CODE REVIEW

**Comment by adrientetar** [comment]
Duplicate of #736.

**Comment by weltkante** [comment]
@adrientetar  #736 is a closed PR, you probably meant #740

**Comment by weltkante** [comment]
Note that #736 is closed so it might be valid to open a new PR (but it should have a better description).

Also note that #736 was closed for discussion in #740 so if that discussion didn't agree on something this PR will probably also be closed.

**Comment by JaggerJo** [comment]
Just want to explain why I think F# should appear on the list:

- You currently can't build UWP apps with F#. (because you can't access the UI related assemblies.) This will change when the Controls are shipped as a NuGet Package. (And as far as I've seen this is planned)

- F# is a .Net language just like VB and C#. If WinUI is just a .Net library why wouldn't it work with F# ? I'm not assuming that the tooling is great or something, but you can use the library. (Just as it is with WPF and F#).

**Comment by jesbis** [comment]
You should be able to reference separate F# libraries, but as noted in #736 we want to make sure that any "officially supported" languages on the roadmap are truly fully supported. 

For F# that would require some new features (e.g. for the Xaml markup compiler and Visual Studio tooling) that .NET doesn't provide for free and which aren't currently planned for the first release of WinUI 3.0, so closing this PR for now. 

However we definitely want to keep discussing how we could improve WinUI's F# support over time in #740. Better F# support is something we can revisit for a future release and/or once WinUI 3 is open source if people are interested in contributing to the effort.

**Pull request closed without merging**
