### PR TITLE
Cleanup readme

### PR DESCRIPTION
**Pull request by Jaiganeshkumaran**
~~Adds information specific to C++/WinRT in the readme.txt file included with the NuGet package.~~ Cleans up content and links to the getting started tutorial.

### CODE REVIEW

**Comment by StephenLPeters** [comment]
@Jaiganeshkumaran is there an associated issue that this PR resolves?

@jevansaks does this cpp winrt requirement make senes?

**Comment by Jaiganeshkumaran** [comment]
> @Jaiganeshkumaran is there an associated issue that this PR resolves?
> 
No there isn't an issue but this is a very small change.

**Comment by chingucoding** [comment]
This is outlined in the walkthrough guide for getting started with WinUI 2 in C++/Winrt: https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/simple-winui-example#edit-pchh-as-necessary

Given that this is not library dependent though, I'm not sure how much value this adds. After all, you would need to do this step with other libraries as well.

**Comment by Jaiganeshkumaran** [comment]
> This is outlined in the walkthrough guide for getting started with WinUI 2 in C++/Winrt: https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/simple-winui-example#edit-pchh-as-necessary
> 
> Given that this is not library dependent though, I'm not sure how much value this adds. After all, you would need to do this step with other libraries as well.

It does add value for me because I don't really know what namespaces are in the Microsoft.UI.Xaml package and providing the list of header files in the readme makes it easier than opening the docs every time I add it to a C++/WinRT project.

**Comment by jevansaks** [comment]
readme.txt already has too much information. Perhaps we can just link out to the getting started documentation and make sure that's up to date?

**Pull request closed without merging**
