### PR TITLE
Fix color animation in HC

### PR DESCRIPTION
**Pull request by beervoley**
## Description

This PR fixes color animation of the Radio Button in High Contrast Mode.

## Screenshots (if appropriate):

HC_RADIO

### CODE REVIEW

**Comment by beervoley** [comment]
@ranjeshj @StephenLPeters @karenbtlai could you please verify the expected behavior?

**Review by StephenLPeters — APPROVED** [review]
:shipit:

**Comment by StephenLPeters** [comment]
Code changes seem reasonable, Unsure if this acheives the design or not.

**Pull request merged**
