### PR TITLE
[innerloop] Fix innerloop by moving styles and adding missing dependencies

### LINKED ISSUE #5919: Unable to run/build MUXControlsInnerLoop due to winrt::ImageIcon
**Describe the bug**

**Steps to reproduce the bug**

**Expected behavior**

**Screenshots**
image

**Version Info**

NuGet package version: 

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  |  |

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2021 Update (19043)            |    |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |  |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

### PR DESCRIPTION
**Pull request by chingucoding**
## Description

There were two problems with the innerloop:
- Some styles were depending on certain controls which are not part of the common innerloop
- Some common controls were missing from the core innerloop

Both are being fixed by this PR by either moving the styles to the control package or adding the controls to the core innerloop.
## Motivation and Context

Closes #5919 
## How Has This Been Tested?

Tested manually.

### CODE REVIEW

**Comment by chingucoding** [comment]
@aqibbanday The issues should be fixed with this PR, feel free to try it out if you want.

**Comment by aqibbanday** [comment]
> @aqibbanday The issues should be fixed with this PR, feel free to try it out if you want.

Sure, thank you.

**Comment by aqibbanday** [comment]
Hi, The project works now, but the inner loop app is blank. i enabled single feature and all features still bank.
image

**Comment by chingucoding** [comment]
What feature-areas did you include in your InnerloopArea.props file?

**Comment by aqibbanday** [comment]
> What feature-areas did you include in your InnerloopArea.props file?

Uncommented the one commented, after that tried all features together still blank.

**Comment by chingucoding** [comment]
Did you close and reopen visual studio after modifying the file and rebuild the app? Unfortunately, Visual Studio does not properly pick up changes to the InnerLoopArea.props file.

Also, there was a bug where the feature area did not build correctly, so you should pull the branch again.

**Comment by aqibbanday** [comment]
> Did you close and reopen visual studio after modifying the file and rebuild the app? Unfortunately, Visual Studio does not properly pick up changes to the InnerLoopArea.props file.
> 
> Also, there was a bug where the feature area did not build correctly, so you should pull the branch again.

Yes, i tried that. Will try this and revert tomorrow

**Comment by aqibbanday** [comment]
> Did you close and reopen visual studio after modifying the file and rebuild the app? Unfortunately, Visual Studio does not properly pick up changes to the InnerLoopArea.props file.
> 
> Also, there was a bug where the feature area did not build correctly, so you should pull the branch again.

Works.

**Review by aqibbanday — APPROVED** [review]
I have tested this and after feedback futher issues were fixed and now the issue is fixed.

**Comment by chingucoding** [comment]
Awesome, thank you for your help in fixing this @aqibbanday !

**Review by bkudiess — APPROVED** [review]

**Comment by bkudiess** [comment]
@chingucoding Can you get main and resolve the conflicts?

**Comment by gabbybilka** [comment]
Thank you for submitting this PR, the current focus of the team is to assist our users in moving from WinUI 2 to WinUI 3. We are closing this PR as it does not address resolving a critical issue for WinUI 2 or WinUI 3.

**Pull request closed without merging**
