### PR TITLE
Update bug_report.yaml for 1.6-exp1

### PR DESCRIPTION
**Pull request by duncanmacmichael**

### CODE REVIEW

**Comment by riverar** [comment]
Can we get this merged in now? @duncanmacmichael

**Comment by duncanmacmichael** [comment]
> Can we get this merged in now? @duncanmacmichael

Ah, yes, thanks for the reminder. I don't have merge permissions but I'll make sure this gets merged to go with the release notes!

**Comment by riverar** [comment]
@duncanmacmichael It's already released, so sooner rather than later is good!

**Comment by duncanmacmichael** [comment]
> @duncanmacmichael It's already released, so sooner rather than later is good!
> 
> cc: @codendone

Right, usually we get these merged same-day as release. Busy week this week, but we'll get it in there :)

**Review by codendone — APPROVED** [review]

**Pull request merged**
