### PR TITLE
Fix TeachingTip title and sub title not being initially collapsed.

### PR DESCRIPTION
**Pull request by StephenLPeters**
Set Title and Subtitle TextBlocks visibility to collapsed in OnApplyTemplate if they are empty. Add a test.

### CODE REVIEW

**Comment by chingucoding** [comment]
What about #3397? They both address the same underlying issues.

**Comment by StephenLPeters** [comment]
ugh, I didn't realize you had already solved this issue... This is a great example of why our current PR state is so bad

**Comment by StephenLPeters** [comment]
I like your PR better, specifically using VSM to set the visibility.

**Comment by chingucoding** [comment]
> ugh, I didn't realize you had already solved this issue... This is a great example of why our current PR state is so bad

Once all open PRs have been merged, I think this won't be an issue anymore.

**Pull request closed without merging**
