### PR TITLE
TreeView: Set IsExpanded when last child has been removed

### LINKED ISSUE #2332: TreeView does not set the IsExpanded property to false when removing the last child node
**Describe the bug**
TreeView does not set the IsExpanded property to false when removing the last child node.

Logically speaking, if there are no child nodes in the TreeView, then the IsExpanded property should be automatically set to false instead of keeping the current value unchanged

**Expected behavior**
set the IsExpanded property to false when removing the last child node

**Screenshots**

**Version Info**

NuGet package version: 

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| November 2019 Update (18363)  | Yes   |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

### PR DESCRIPTION
**Pull request by chingucoding**
## Description

Add code that set's the IsExpanded of a node to false when it's last child has been removed.
## Motivation and Context

Fixes #2332 
## How Has This Been Tested?

Add new API test

### CODE REVIEW

**Comment by Felix-Dev** [comment]
My WinUI build system is currently broken so I can't check myself. What happens when the items source for a treeview item is changed and the item was previously expanded? Does the IsExpanded state change to collapsed in this situation?

**Comment by chingucoding** [comment]
In what scenario exactly? If you remove and readd the collection, I don't think we could restore the IsExpanded state anyway. But If you look at the tests, in cases where the list changes, I think in most cases the IsExpanded state won't change.

**Comment by Felix-Dev** [comment]
Managed to build WinUI and the test app again, seems fine to me.

**Pull request merged**
