### PR TITLE
Fix WebView2 version number mismatch

### PR DESCRIPTION
**Pull request by softworkz**
Fixes https://github.com/microsoft/microsoft-ui-xaml/issues/9437

### CODE REVIEW

**Comment by codendone** [comment]
It looks like this change may have been made against the release/1.5-experimental2 drop of the source. The update to this WebView2 version was in 1.5-preview1 and later, and shows in the latest sync of the 1.5-stable branch.

**Comment by softworkz** [comment]
> It looks like this change may have been made against the release/1.5-experimental2 drop of the source. The update to this WebView2 version was in 1.5-preview1 and later, and shows in the latest sync of the 1.5-stable branch.

You are right. But this is weird - how can GitHub show this as a change then agains the 1.5 stable branch...?

image

I'm very confused...

**Comment by codendone** [comment]
Yes, if you could explain that to me, that would be great. :) Your change looked completely correct to me and it took me a while to prove to myself that latest 1.5-stable branch is correct. I don't know how GitHub is showing it this way.

(Aside: Given that this version appears to be correct in 1.5.0 and 1.5.1, I don't know what is causing this problem. The issue will need to be investigated.)

**Comment by softworkz** [comment]
Now I know why: Because you have committed and pushed this to the repo here only yesterday - AFTER my PR. 
PRs are always shown against the state which they were made against. 

image

The commit which updates the version number has the title **1.5-preview1**.  But it was committed only yesterday - after I made this PR. Can this be a coincidence?

In the end it's still not clear which value the version had at the time then the 1.5 release was compiled.

**Comment by softworkz** [comment]
It's a really weird coincidence, that right after my PR commits are pushed having this change but commited only after my PR.

So - either somebody wanted to cover a mistake. Or I'm on the wrong track and there's another cause for the problem.

**Comment by codendone** [comment]
Interesting. Git tells me that the 1.5-preview1 commit happened on February 13 and had the updated value, but maybe there was a problem in the source publishing pipeline which didn't push everything until the 1.5.1 publish yesterday?

**Comment by softworkz** [comment]
> Interesting. Git tells me that the 1.5-preview1 commit happened on February 13 and had the updated value, but maybe there was a problem in the source publishing pipeline which didn't push everything until the 1.5.1 publish yesterday?

Yes, Feb 13, that's what I mean.  Sure, it can be that the publishing was hanging for some reason. But exactly in the moment after my PR, it suddenly starts working again?

Can you look it up in the original repo what the version was at the time when it was built?

**Comment by codendone** [comment]
The correct version is in the original build repo as of January 31, before the 1.5-preview1 and later builds. And I see the correct version of the Microsoft.Web.WebView2.Core.dll included in the 1.5.0 and 1.5.1 package installs. Everything looks correct to me (from just the perspective of code and file inspection).

**Comment by softworkz** [comment]
Sorry then, I was on a wrong track - I just realize. The WinAppSDK 1.5 was only built on 28 Feb. I thought it had been built earlier.
Probably that's because I had made the other 2 PRs against the branch "1.5-stable" even though it wasn't stable at that time...

Nevermind, then it must have a different cause.

Thanks a lot for looking into it.

**Pull request closed without merging**
