### PR TITLE
Keyboard text alignment

### PR DESCRIPTION
**Pull request by Sytta**
## Description
Add HorizontalTextAlignment="Right" in the style of KeyboardAcceleratorTextLabel for CommandBarFlyoutAppBarButtonStyleBase, CommandBarFlyoutAppBarToggleButtonStyleBase, DefaultAppBarButtonStyle, DefaultAppBarToggleButtonStyle, MediaControlAppBarButtonStyle and their uses cases.

Add HorizontalTextAlignment="Right" in the style of KeyboardAcceleratorTextBlock for DefaultMenuFlyoutItemStyle, DefaultToggleMenuFlyoutItemStyle, MenuFlyoutItemRevealStyle, ToggleMenuFlyoutItemRevealStyle, DefaultRadioMenuFlyoutItemStyle and theiruse cases.

## Motivation and Context

The text alignment of the keyboard accelerator text would switch to center even if the HorizontalAlignment has been set to "Right". 
Expected:
image
Actual:
image
This is because the HorizontalAlignment of the textblock is right, but the HorizontalTextAlignment is not aligned to right.

## How Has This Been Tested?

Tested with rtl and ltr by [tashatitova](https://github.com/tashatitova) as we can observe below:
0a4e8a2d-3783-4c35-803c-2485d571462d
ef0d5034-2288-4fe5-99de-aed8226d862f

### CODE REVIEW

**Comment by tashatitova** [comment]
The only thing to test I can think of would be right to left flow. @karenbtlai  is there an easy way to test this in MUX solution?

**Comment by Sytta** [comment]
> The only thing to test I can think of would be right to left flow. @karenbtlai is there an easy way to test this in MUX solution?

I've only tested in the current UWP app we are working on, we basically copied the the whole styling and added the HorizontalTextAlignment="Right" which effectively made the text align to the right.

**Review by tashatitova — APPROVED** [review]

**Comment by tashatitova** [comment]
> 

it's actually quite easy to test right to left (RTL) by adding FlowDirection=RTL to the test panel containing the test items. I ran this change on a bunch of controls and they look good
rtl-fixed
after
before
.

**Comment by llongley** [comment]
> Can we please run the tests again? I had the compiler error "Member 'HorizontalTextAlignment' on type 'Windows.UI.Xaml.Controls.ITextBlock6' is defined under contract 'Windows.Foundation.UniversalApiContract' version '5.0.0.0', but the contract version for the targeted min version is '4.0.0.0'!" so I think I have to remove the HorizontalTextAlignment on Textblocks without contract6Present in my latest commit. Please tell me if there's a better way to resolve this issue so I can keep the HorizontalTextAlignment attribute.

You can add contract constraints to properties as well.  For example, you can do this:

```
xmlns:contract5Present="http://schemas.microsoft.com/winfx/2006/xaml/presentation?IsApiContractPresent(Windows.Foundation.UniversalApiContract,5)"

<TextBlock xmlns:contract5Present:HorizontalTextAlignment="Right" />
```

That should allow you to put it everywhere.

**Comment by Sytta** [comment]
> > Can we please run the tests again? I had the compiler error "Member 'HorizontalTextAlignment' on type 'Windows.UI.Xaml.Controls.ITextBlock6' is defined under contract 'Windows.Foundation.UniversalApiContract' version '5.0.0.0', but the contract version for the targeted min version is '4.0.0.0'!" so I think I have to remove the HorizontalTextAlignment on Textblocks without contract6Present in my latest commit. Please tell me if there's a better way to resolve this issue so I can keep the HorizontalTextAlignment attribute.
> 
> You can add contract constraints to properties as well. For example, you can do this:
> 
> ```
> xmlns:contract5Present="http://schemas.microsoft.com/winfx/2006/xaml/presentation?IsApiContractPresent(Windows.Foundation.UniversalApiContract,5)"
> 
> <TextBlock contract5Present:HorizontalTextAlignment="Right" />
> ```
> 
> That should allow you to put it everywhere.

Thank you! I put contract5Present before every HorizontalTextAlignment I added. I'm not very familiar yet with xaml contract versions, hope this time it will build fine :)

**Comment by Sytta** [comment]
Any news?

**Comment by estebanm123** [comment]
Bump - is there anything holding back the merge?

**Review by karenbtlai — APPROVED** [review]

**Pull request merged**
