### PR TITLE
Fixes several bugs

### PR DESCRIPTION
**Pull request by teaP**
Fixes the following:
#1709, the popup now extends outside the window bounds, though only on 19h1 and higher.
#1707, listening to PreviewKeyDown fixes this issue.
#1706, removed extra tab stop on the control.

Partial fix to #1694. I copied directly from our template of TextBox instead of the style from the SDK (which caused some other updates too.) The control now has correct highlighting and the popup buttons have a border (image is from RS2):
image

Inline buttons still don't look great, though. Will address in a later fix.
image

### CODE REVIEW

**Comment by StephenLPeters** [comment]
In the photo provided in the PR description the flyout does not have rounded corners, is that another bug?

**Comment by StephenLPeters** [comment]
>             StepValue(SmallChange());

If step value doesn't result in a change, should we still mark the event as handled? or should we let text block maybe handle the key since we didn't actually do anything.

---
Refers to: dev/NumberBox/NumberBox.cpp:380 in 929bd35. [](commit_id = 929bd3549254d7225c0b285dc13e20e485abab82, deletion_comment = False)

**Comment by teaP** [comment]
> In the photo provided in the PR description the flyout does not have rounded corners, is that another bug?

Actually yes, the screenshot is from RS2 but since CornerRadius is on Grid since the beginning I can add it. :)

**Comment by teaP** [comment]
> > ```
> >         StepValue(SmallChange());
> > ```
> 
> If step value doesn't result in a change, should we still mark the event as handled? or should we let text block maybe handle the key since we didn't actually do anything.

Hmm, I'm not sure. I think it would be weird if someone else were getting the events only when we happened to be at min/max. So either always handle it or never do?

**Comment by StephenLPeters** [comment]
> > > ```
> > >         StepValue(SmallChange());
> > > ```
> > 
> > 
> > If step value doesn't result in a change, should we still mark the event as handled? or should we let text block maybe handle the key since we didn't actually do anything.
> 
> Hmm, I'm not sure. I think it would be weird if someone else were getting the events only when we happened to be at min/max. So either always handle it or never do?

Sounds good

**Pull request merged**
